In [4]:
import pandas as pd

customers = pd.read_csv("../data/customers.csv")
accounts = pd.read_csv("../data/accounts.csv")
transactions = pd.read_csv("../data/Transactions.csv")
loans = pd.read_csv("../data/Loans.csv")

print("Customers:", customers.shape)
print("Accounts:", accounts.shape)
print("Transactions:", transactions.shape)
print("Loans:", loans.shape)

Customers: (10000, 7)
Accounts: (13000, 6)
Transactions: (5000, 6)
Loans: (2000, 8)

In [5]:
print("CUSTOMERS")
print(customers.columns.tolist())

print("\nACCOUNTS")
print(accounts.columns.tolist())

print("\nTRANSACTIONS")
print(transactions.columns.tolist())

print("\nLOANS")
print(loans.columns.tolist())

CUSTOMERS
['customer_id', 'age', 'gender', 'city', 'occupation', 'annual_income', 'customer_since']

ACCOUNTS
['account_id', 'customer_id', 'account_type', 'balance', 'account_opening_date', 'status']

TRANSACTIONS
['transaction_id', 'account_id', 'transaction_date', 'transaction_type', 'amount', 'balance_after_transaction']

LOANS
['loan_id', 'customer_id', 'loan_type', 'loan_amount', 'interest_rate', 'loan_date', 'loan_status', 'outstanding_amount']

In [6]:
print("CUSTOMERS")
customers.info()

print("\nACCOUNTS")
accounts.info()

print("\nTRANSACTIONS")
transactions.info()

print("\nLOANS")
loans.info()

CUSTOMERS
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     10000 non-null  str
 1   age             10000 non-null  int64
 2   gender          10000 non-null  str
 3   city            10000 non-null  str
 4   occupation      10000 non-null  str
 5   annual_income   10000 non-null  int64
 6   customer_since  10000 non-null  str
dtypes: int64(2), str(5)
memory usage: 547.0 KB

ACCOUNTS
<class 'pandas.DataFrame'>
RangeIndex: 13000 entries, 0 to 12999
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   account_id            13000 non-null  str
 1   customer_id           13000 non-null  str
 2   account_type          13000 non-null  str
 3   balance               13000 non-null  float64
 4   account_opening_date  13000 non-null  str
 5   status                13000 non-null  str
dtypes: float64(1), str(5)
memory usage: 609.5 KB

TRANSACTIONS
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   transaction_id             5000 non-null   str
 1   account_id                 5000 non-null   str
 2   transaction_date           5000 non-null   str
 3   transaction_type           5000 non-null   str
 4   amount                     5000 non-null   float64
 5   balance_after_transaction  5000 non-null   float64
dtypes: float64(2), str(4)
memory usage: 234.5 KB

LOANS
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   loan_id             2000 non-null   str
 1   customer_id         2000 non-null   str
 2   loan_type           2000 non-null   str
 3   loan_amount         2000 non-null   float64
 4   interest_rate       2000 non-null   float64
 5   loan_date           2000 non-null   str
 6   loan_status         2000 non-null   str
 7   outstanding_amount  2000 non-null   float64
dtypes: float64(3), str(5)
memory usage: 125.1 KB

In [7]:
customers["customer_since"] = pd.to_datetime(customers["customer_since"])
accounts["account_opening_date"] = pd.to_datetime(accounts["account_opening_date"])
transactions["transaction_date"] = pd.to_datetime(transactions["transaction_date"])
loans["loan_date"] = pd.to_datetime(loans["loan_date"])

print("Date conversion completed.")
print(customers["customer_since"].dtype)
print(accounts["account_opening_date"].dtype)
print(transactions["transaction_date"].dtype)
print(loans["loan_date"].dtype)

Date conversion completed.
datetime64[us]
datetime64[us]
datetime64[us]
datetime64[us]

In [8]:
print("Duplicate records:")
print("Customers:", customers.duplicated().sum())
print("Accounts:", accounts.duplicated().sum())
print("Transactions:", transactions.duplicated().sum())
print("Loans:", loans.duplicated().sum())

Duplicate records:
Customers: 0
Accounts: 0
Transactions: 0
Loans: 0

In [9]:
print("Gender:")
print(customers["gender"].unique())

print("\nAccount Type:")
print(accounts["account_type"].unique())

print("\nAccount Status:")
print(accounts["status"].unique())

print("\nTransaction Type:")
print(transactions["transaction_type"].unique())

print("\nLoan Type:")
print(loans["loan_type"].unique())

print("\nLoan Status:")
print(loans["loan_status"].unique())

Gender:
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

Account Type:
<StringArray>
['Current', 'Savings']
Length: 2, dtype: str

Account Status:
<StringArray>
['Active', 'Inactive']
Length: 2, dtype: str

Transaction Type:
<StringArray>
['Credit', 'Transfer', 'Debit']
Length: 3, dtype: str

Loan Type:
<StringArray>
['Personal', 'Business', 'Home', 'Auto', 'Education']
Length: 5, dtype: str

Loan Status:
<StringArray>
['Closed', 'Active', 'Default']
Length: 3, dtype: str

In [10]:
customer_summary = customers[["age", "annual_income"]].describe()

print(customer_summary)

                age  annual_income
count  10000.000000   1.000000e+04
mean      43.038200   1.390827e+06
std       12.895611   6.531931e+05
min       21.000000   2.500730e+05
25%       32.000000   8.257238e+05
50%       43.000000   1.406660e+06
75%       54.000000   1.958803e+06
max       65.000000   2.499780e+06

In [11]:
occupation_summary = (
    customers["occupation"]
    .value_counts()
    .reset_index()
)

occupation_summary.columns = ["occupation", "customer_count"]

print(occupation_summary)

                occupation  customer_count
0            Self Employed            1062
1  Healthcare Professional            1048
2         Private Employee            1039
3                    Other            1026
4               Consultant            1004
5                 Engineer             984
6                  Teacher             975
7           Business Owner             973
8          IT Professional             957
9      Government Employee             932

In [12]:
#Loan portfolio by loan type

loan_type_summary = (
    loans.groupby("loan_type")
    .agg(
        total_loans=("loan_id", "count"),
        total_loan_amount=("loan_amount", "sum"),
        total_outstanding=("outstanding_amount", "sum")
    )
    .reset_index()
)

print(loan_type_summary)

#note:e+08 simply means × 100,000,000.

   loan_type  total_loans  total_loan_amount  total_outstanding
0       Auto          380       5.026141e+08       2.308218e+08
1   Business          386       4.652950e+08       2.047537e+08
2  Education          432       5.596469e+08       2.495840e+08
3       Home          404       4.989542e+08       2.194644e+08
4   Personal          398       4.979143e+08       2.316862e+08

In [13]:
pd.options.display.float_format = '{:,.2f}'.format

print(loan_type_summary)

   loan_type  total_loans  total_loan_amount  total_outstanding
0       Auto          380     502,614,143.63     230,821,826.11
1   Business          386     465,294,953.81     204,753,693.71
2  Education          432     559,646,942.58     249,583,958.14
3       Home          404     498,954,249.05     219,464,414.11
4   Personal          398     497,914,341.58     231,686,157.28

In [14]:
# Loan status analysis

loan_status_summary = (
    loans.groupby("loan_status")
    .agg(
        total_loans=("loan_id", "count"),
        total_loan_amount=("loan_amount", "sum"),
        total_outstanding=("outstanding_amount", "sum")
    )
    .reset_index()
)

print(loan_status_summary)

  loan_status  total_loans  total_loan_amount  total_outstanding
0      Active         1214   1,532,201,958.29     698,240,731.73
1      Closed          596     751,160,164.17     328,895,370.00
2     Default          190     241,062,508.19     109,173,947.62

In [15]:
#Calculate the overall default rate

total_loans = len(loans)
default_loans = (loans["loan_status"] == "Default").sum()

default_rate = (default_loans / total_loans) * 100

print(f"Total Loans: {total_loans:,}")
print(f"Default Loans: {default_loans:,}")
print(f"Default Rate: {default_rate:.2f}%")

Total Loans: 2,000
Default Loans: 190
Default Rate: 9.50%

In [16]:
# Outstanding Amount by Loan Status

outstanding_by_status = loans.groupby('loan_status')['outstanding_amount'].agg(
    total_outstanding='sum',
    average_outstanding='mean'
).reset_index()

outstanding_by_status

  loan_status  total_outstanding  average_outstanding
0      Active     698,240,731.73           575,157.11
1      Closed     328,895,370.00           551,837.87
2     Default     109,173,947.62           574,599.72

In [17]:
# Average Interest Rate by Loan Type

interest_by_type = loans.groupby('loan_type')['interest_rate'].agg(
    average_interest_rate='mean'
).reset_index()

interest_by_type

   loan_type  average_interest_rate
0       Auto                  12.55
1   Business                  12.76
2  Education                  12.50
3       Home                  12.57
4   Personal                  12.59

In [18]:
# Total and Average Loan Amount by Loan Type

loan_amount_by_type = loans.groupby('loan_type')['loan_amount'].agg(
    total_loan_amount='sum',
    average_loan_amount='mean'
).reset_index()

loan_amount_by_type

   loan_type  total_loan_amount  average_loan_amount
0       Auto     502,614,143.63         1,322,668.80
1   Business     465,294,953.81         1,205,427.34
2  Education     559,646,942.58         1,295,479.03
3       Home     498,954,249.05         1,235,035.27
4   Personal     497,914,341.58         1,251,041.06

In [19]:
# Outstanding Amount by Loan Type

outstanding_by_type = loans.groupby('loan_type')['outstanding_amount'].agg(
    total_outstanding='sum',
    average_outstanding='mean'
).reset_index()

outstanding_by_type

   loan_type  total_outstanding  average_outstanding
0       Auto     230,821,826.11           607,425.86
1   Business     204,753,693.71           530,449.98
2  Education     249,583,958.14           577,740.64
3       Home     219,464,414.11           543,228.75
4   Personal     231,686,157.28           582,126.02

In [20]:
# Loan Status Distribution by Loan Type

loan_status_by_type = pd.crosstab(
    loans['loan_type'],
    loans['loan_status']
)

loan_status_by_type

loan_status  Active  Closed  Default
loan_type
Auto            225     116       39
Business        224     131       31
Education       254     142       36
Home            249     111       44
Personal        262      96       40

In [21]:
# Default Rate by Loan Type

default_rate_by_type = loans.groupby('loan_type').agg(
    total_loans=('loan_id', 'count'),
    defaulted_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

default_rate_by_type['default_rate'] = (
    default_rate_by_type['defaulted_loans'] /
    default_rate_by_type['total_loans'] * 100
)

default_rate_by_type

   loan_type  total_loans  defaulted_loans  default_rate
0       Auto          380               39         10.26
1   Business          386               31          8.03
2  Education          432               36          8.33
3       Home          404               44         10.89
4   Personal          398               40         10.05

In [22]:
# Interest Rate Distribution

interest_rate_summary = loans['interest_rate'].agg(
    minimum_rate='min',
    maximum_rate='max',
    average_rate='mean',
    median_rate='median'
)

interest_rate_summary

minimum_rate    7.01
maximum_rate   18.00
average_rate   12.59
median_rate    12.68
Name: interest_rate, dtype: float64

In [23]:
# Average Interest Rate by Loan Status

interest_by_status = loans.groupby('loan_status')['interest_rate'].agg(
    average_interest_rate='mean'
).reset_index()

interest_by_status

  loan_status  average_interest_rate
0      Active                  12.62
1      Closed                  12.60
2     Default                  12.40

In [24]:
# Average Loan Amount by Loan Status

loan_amount_by_status = loans.groupby('loan_status')['loan_amount'].agg(
    total_loan_amount='sum',
    average_loan_amount='mean'
).reset_index()

loan_amount_by_status

  loan_status  total_loan_amount  average_loan_amount
0      Active   1,532,201,958.29         1,262,110.34
1      Closed     751,160,164.17         1,260,335.85
2     Default     241,062,508.19         1,268,750.04

In [25]:
# Loan Amount Share by Loan Status

loan_amount_share = loans.groupby('loan_status')['loan_amount'].sum().reset_index()

total_loan_amount = loan_amount_share['loan_amount'].sum()

loan_amount_share['loan_amount_percentage'] = (
    loan_amount_share['loan_amount'] / total_loan_amount * 100
).round(2)

loan_amount_share

  loan_status      loan_amount  loan_amount_percentage
0      Active 1,532,201,958.29                   60.70
1      Closed   751,160,164.17                   29.76
2     Default   241,062,508.19                    9.55

In [26]:
# Outstanding Amount Share by Loan Status

outstanding_share = loans.groupby('loan_status')['outstanding_amount'].sum().reset_index()

total_outstanding = outstanding_share['outstanding_amount'].sum()

outstanding_share['outstanding_amount_percentage'] = (
    outstanding_share['outstanding_amount'] / total_outstanding * 100
).round(2)

outstanding_share

  loan_status  outstanding_amount  outstanding_amount_percentage
0      Active      698,240,731.73                          61.45
1      Closed      328,895,370.00                          28.94
2     Default      109,173,947.62                           9.61

In [27]:
# Outstanding Ratio by Loan Status

outstanding_ratio = loans.groupby('loan_status').agg(
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum')
).reset_index()

outstanding_ratio['outstanding_ratio'] = (
    outstanding_ratio['total_outstanding'] /
    outstanding_ratio['total_loan_amount'] * 100
).round(2)

outstanding_ratio

  loan_status  total_loan_amount  total_outstanding  outstanding_ratio
0      Active   1,532,201,958.29     698,240,731.73              45.57
1      Closed     751,160,164.17     328,895,370.00              43.78
2     Default     241,062,508.19     109,173,947.62              45.29

In [28]:
# Loan Status Count by Loan Type

loan_status_by_type = pd.crosstab(
    loans['loan_type'],
    loans['loan_status']
)

loan_status_by_type

loan_status  Active  Closed  Default
loan_type
Auto            225     116       39
Business        224     131       31
Education       254     142       36
Home            249     111       44
Personal        262      96       40

In [29]:
# Loan Amount vs Outstanding Amount by Loan Type

loan_amount_vs_outstanding = loans.groupby('loan_type').agg(
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding_amount=('outstanding_amount', 'sum')
).reset_index()

loan_amount_vs_outstanding

   loan_type  total_loan_amount  total_outstanding_amount
0       Auto     502,614,143.63            230,821,826.11
1   Business     465,294,953.81            204,753,693.71
2  Education     559,646,942.58            249,583,958.14
3       Home     498,954,249.05            219,464,414.11
4   Personal     497,914,341.58            231,686,157.28

In [30]:
# Outstanding Ratio by Loan Type

outstanding_ratio_by_type = loans.groupby('loan_type').agg(
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding_amount=('outstanding_amount', 'sum')
).reset_index()

outstanding_ratio_by_type['outstanding_ratio'] = (
    outstanding_ratio_by_type['total_outstanding_amount'] /
    outstanding_ratio_by_type['total_loan_amount'] * 100
).round(2)

outstanding_ratio_by_type

   loan_type  total_loan_amount  total_outstanding_amount  outstanding_ratio
0       Auto     502,614,143.63            230,821,826.11              45.92
1   Business     465,294,953.81            204,753,693.71              44.01
2  Education     559,646,942.58            249,583,958.14              44.60
3       Home     498,954,249.05            219,464,414.11              43.98
4   Personal     497,914,341.58            231,686,157.28              46.53

In [31]:
# Loan Amount by Loan Type and Status

loan_amount_type_status = pd.pivot_table(
    loans,
    values='loan_amount',
    index='loan_type',
    columns='loan_status',
    aggfunc='sum'
).round(2)

loan_amount_type_status

loan_status         Active         Closed       Default
loan_type
Auto        308,799,697.25 148,060,430.07 45,754,016.31
Business    264,728,915.08 163,017,176.57 37,548,862.16
Education   345,106,125.19 171,602,218.52 42,938,598.87
Home        296,428,123.27 140,923,227.28 61,602,898.50
Personal    317,139,097.50 127,557,111.73 53,218,132.35

In [32]:
# Outstanding Amount by Loan Type and Status

outstanding_type_status = pd.pivot_table(
    loans,
    values='outstanding_amount',
    index='loan_type',
    columns='loan_status',
    aggfunc='sum'
).round(2)

outstanding_type_status

loan_status         Active        Closed       Default
loan_type
Auto        142,454,864.09 63,903,552.83 24,463,409.19
Business    121,498,983.75 66,189,223.25 17,065,486.71
Education   151,476,725.81 76,408,576.71 21,698,655.62
Home        133,518,902.68 62,508,572.48 23,436,938.95
Personal    149,291,255.40 59,885,444.73 22,509,457.15

In [33]:
# Average Outstanding Amount by Loan Type

avg_outstanding_by_type = loans.groupby('loan_type')['outstanding_amount'].agg(
    average_outstanding_amount='mean'
).reset_index()

avg_outstanding_by_type

   loan_type  average_outstanding_amount
0       Auto                  607,425.86
1   Business                  530,449.98
2  Education                  577,740.64
3       Home                  543,228.75
4   Personal                  582,126.02

In [34]:
# Default Outstanding Ratio by Loan Type

default_outstanding_ratio = loans.groupby('loan_type').agg(
    total_outstanding=('outstanding_amount', 'sum'),
    default_outstanding=('outstanding_amount',
                         lambda x: x[loans.loc[x.index, 'loan_status'] == 'Default'].sum())
).reset_index()

default_outstanding_ratio['default_outstanding_ratio'] = (
    default_outstanding_ratio['default_outstanding'] /
    default_outstanding_ratio['total_outstanding'] * 100
).round(2)

default_outstanding_ratio

,loan_type,total_outstanding,default_outstanding,default_outstanding_ratio
0,Auto,"230,821,826.11","24,463,409.19",10.60
1,Business,"204,753,693.71","17,065,486.71",8.33
2,Education,"249,583,958.14","21,698,655.62",8.69
3,Home,"219,464,414.11","23,436,938.95",10.68
4,Personal,"231,686,157.28","22,509,457.15",9.72

In [35]:
# Average Defaulted Loan Amount by Loan Type

avg_default_loan = loans[loans['loan_status'] == 'Default'].groupby(
    'loan_type'
)['loan_amount'].agg(
    default_loan_count='count',
    average_default_loan_amount='mean'
).reset_index()

avg_default_loan['average_default_loan_amount'] = (
    avg_default_loan['average_default_loan_amount'].round(2)
)

avg_default_loan

   loan_type  default_loan_count  average_default_loan_amount
0       Auto                  39                 1,173,179.91
1   Business                  31                 1,211,253.62
2  Education                  36                 1,192,738.86
3       Home                  44                 1,400,065.88
4   Personal                  40                 1,330,453.31

In [36]:
# Average Outstanding Amount for Defaulted Loans by Loan Type

avg_default_outstanding = loans[
    loans['loan_status'] == 'Default'
].groupby('loan_type')['outstanding_amount'].agg(
    default_loan_count='count',
    average_default_outstanding='mean'
).reset_index()

avg_default_outstanding['average_default_outstanding'] = (
    avg_default_outstanding['average_default_outstanding'].round(2)
)

avg_default_outstanding

   loan_type  default_loan_count  average_default_outstanding
0       Auto                  39                   627,266.90
1   Business                  31                   550,499.57
2  Education                  36                   602,740.43
3       Home                  44                   532,657.70
4   Personal                  40                   562,736.43

In [37]:
# Average Loan Amount by Loan Type

average_loan_by_type = loans.groupby('loan_type')['loan_amount'].agg(
    total_loans='count',
    average_loan_amount='mean'
).reset_index()

average_loan_by_type

   loan_type  total_loans  average_loan_amount
0       Auto          380         1,322,668.80
1   Business          386         1,205,427.34
2  Education          432         1,295,479.03
3       Home          404         1,235,035.27
4   Personal          398         1,251,041.06

In [38]:
# Default Rate by Interest Rate Group

loans['interest_rate_group'] = pd.cut(
    loans['interest_rate'],
    bins=[0, 8, 10, 12, 14, 16, 20],
    labels=['<=8%', '8-10%', '10-12%', '12-14%', '14-16%', '>16%']
)

interest_risk = loans.groupby('interest_rate_group', observed=True).agg(
    total_loans=('loan_id', 'count'),
    default_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

interest_risk['default_rate'] = (
    interest_risk['default_loans'] /
    interest_risk['total_loans'] * 100
).round(2)

interest_risk

  interest_rate_group  total_loans  default_loans  default_rate
0                <=8%          159             21         13.21
1               8-10%          343             33          9.62
2              10-12%          380             38         10.00
3              12-14%          359             25          6.96
4              14-16%          411             37          9.00
5                >16%          348             36         10.34

In [39]:
# Default Rate by Loan Amount Group

loans['loan_amount_group'] = pd.qcut(
    loans['loan_amount'],
    q=5,
    labels=['Very Low', 'Low', 'Medium', 'High', 'Very High']
)

loan_amount_risk = loans.groupby('loan_amount_group', observed=True).agg(
    total_loans=('loan_id', 'count'),
    default_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

loan_amount_risk['default_rate'] = (
    loan_amount_risk['default_loans'] /
    loan_amount_risk['total_loans'] * 100
).round(2)

loan_amount_risk

  loan_amount_group  total_loans  default_loans  default_rate
0          Very Low          400             43         10.75
1               Low          400             33          8.25
2            Medium          400             42         10.50
3              High          400             33          8.25
4         Very High          400             39          9.75

In [40]:
customers = pd.read_csv('../Data/customers.csv')

customers.head()

,customer_id,age,gender,city,occupation,annual_income,customer_since
0,C10001,59,Male,Delhi,Teacher,418183,2015-02-21
1,C10002,49,Male,Kochi,Teacher,1585307,2010-07-08
2,C10003,35,Female,Kolkata,Other,833642,2013-12-11
3,C10004,63,Male,Coimbatore,Self Employed,1061744,2013-05-05
4,C10005,28,Male,Delhi,Self Employed,357764,2017-02-10

In [42]:
# Default Rate by Customer Income Group

loans_income = loans.merge(
    customers[['customer_id', 'annual_income']],
    on='customer_id',
    how='left'
)

loans_income['income_group'] = pd.qcut(
    loans_income['annual_income'],
    q=5,
    labels=['Very Low', 'Low', 'Medium', 'High', 'Very High']
)

income_risk = loans_income.groupby('income_group', observed=True).agg(
    total_loans=('loan_id', 'count'),
    default_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

income_risk['default_rate'] = (
    income_risk['default_loans'] /
    income_risk['total_loans'] * 100
).round(2)

income_risk

  income_group  total_loans  default_loans  default_rate
0     Very Low          400             37          9.25
1          Low          400             30          7.50
2       Medium          400             41         10.25
3         High          400             44         11.00
4    Very High          400             38          9.50

In [43]:
# Loan-to-Income Ratio and Default Risk

loans_income['loan_to_income_ratio'] = (
    loans_income['loan_amount'] / loans_income['annual_income']
)

loans_income['loan_to_income_group'] = pd.qcut(
    loans_income['loan_to_income_ratio'],
    q=5,
    labels=['Very Low', 'Low', 'Medium', 'High', 'Very High']
)

loan_income_risk = loans_income.groupby(
    'loan_to_income_group',
    observed=True
).agg(
    total_loans=('loan_id', 'count'),
    default_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

loan_income_risk['default_rate'] = (
    loan_income_risk['default_loans'] /
    loan_income_risk['total_loans'] * 100
).round(2)

loan_income_risk

  loan_to_income_group  total_loans  default_loans  default_rate
0             Very Low          400             41         10.25
1                  Low          400             40         10.00
2               Medium          400             43         10.75
3                 High          400             27          6.75
4            Very High          400             39          9.75

In [44]:
# Customer Loan Exposure and Default Risk

customer_exposure = loans.groupby('customer_id').agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum'),
    default_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

customer_exposure['default_rate'] = (
    customer_exposure['default_loans'] /
    customer_exposure['total_loans'] * 100
).round(2)

customer_exposure.sort_values(
    'total_loan_amount',
    ascending=False
).head(10)

,customer_id,total_loans,total_loan_amount,total_outstanding,default_loans,default_rate
1030,C15654,3,"6,101,394.22","1,021,917.04",0,0.00
493,C12656,3,"5,939,952.03","1,107,942.04",0,0.00
1704,C19425,3,"5,823,962.06","2,300,630.81",0,0.00
346,C11961,3,"5,454,667.70","2,700,666.75",0,0.00
553,C12956,4,"4,912,742.08","1,637,348.55",0,0.00
602,C13329,2,"4,725,252.80","2,816,292.86",0,0.00
1788,C19897,2,"4,681,551.19","795,971.65",1,50.00
1365,C17549,2,"4,628,008.14","1,544,669.69",0,0.00
187,C11159,2,"4,621,069.84","2,031,803.99",0,0.00
1047,C15794,2,"4,602,378.33","1,508,074.84",0,0.00

In [45]:
# Loan Status Distribution by Loan Type

loan_type_status = pd.crosstab(
    loans['loan_type'],
    loans['loan_status']
).reset_index()

loan_type_status

loan_status  loan_type  Active  Closed  Default
0                 Auto     225     116       39
1             Business     224     131       31
2            Education     254     142       36
3                 Home     249     111       44
4             Personal     262      96       40

In [46]:
# Outstanding Exposure by Loan Status

outstanding_by_status = loans.groupby('loan_status').agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum'),
    average_outstanding=('outstanding_amount', 'mean')
).reset_index()

outstanding_by_status

,loan_status,total_loans,total_loan_amount,total_outstanding,average_outstanding
0,Active,1214,"1,532,201,958.29","698,240,731.73","575,157.11"
1,Closed,596,"751,160,164.17","328,895,370.00","551,837.87"
2,Default,190,"241,062,508.19","109,173,947.62","574,599.72"

In [47]:
# Outstanding Amount as % of Original Loan Amount

loans['outstanding_ratio'] = (
    loans['outstanding_amount'] / loans['loan_amount'] * 100
)

loans['outstanding_ratio'].describe()

count   2,000.00
mean       45.37
std        25.75
min         0.00
25%        23.35
50%        45.75
75%        67.43
max        89.91
Name: outstanding_ratio, dtype: float64

In [48]:
# Average Outstanding Ratio by Loan Type

outstanding_ratio_by_type = loans.groupby('loan_type')['outstanding_ratio'].agg(
    average_outstanding_ratio='mean'
).reset_index()

outstanding_ratio_by_type['average_outstanding_ratio'] = (
    outstanding_ratio_by_type['average_outstanding_ratio'] * 100
).round(2)

outstanding_ratio_by_type

   loan_type  average_outstanding_ratio
0       Auto                   4,586.30
1   Business                   4,473.38
2  Education                   4,578.22
3       Home                   4,395.58
4   Personal                   4,648.50

In [49]:
# Average Outstanding Ratio by Loan Status

outstanding_ratio_by_status = loans.groupby('loan_status')['outstanding_ratio'].agg(
    average_outstanding_ratio='mean'
).reset_index()

outstanding_ratio_by_status['average_outstanding_ratio'] = (
    outstanding_ratio_by_status['average_outstanding_ratio'] * 100
).round(2)

outstanding_ratio_by_status

  loan_status  average_outstanding_ratio
0      Active                   4,589.10
1      Closed                   4,432.83
2     Default                   4,526.81

In [50]:
# Outstanding Amount Ratio by Loan Type

outstanding_amount_ratio = loans.groupby('loan_type').agg(
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding_amount=('outstanding_amount', 'sum')
).reset_index()

outstanding_amount_ratio['outstanding_amount_ratio'] = (
    outstanding_amount_ratio['total_outstanding_amount'] /
    outstanding_amount_ratio['total_loan_amount'] * 100
).round(2)

outstanding_amount_ratio

,loan_type,total_loan_amount,total_outstanding_amount,outstanding_amount_ratio
0,Auto,"502,614,143.63","230,821,826.11",45.92
1,Business,"465,294,953.81","204,753,693.71",44.01
2,Education,"559,646,942.58","249,583,958.14",44.60
3,Home,"498,954,249.05","219,464,414.11",43.98
4,Personal,"497,914,341.58","231,686,157.28",46.53

In [51]:
# Average Interest Rate by Loan Status

interest_by_status = loans.groupby('loan_status')['interest_rate'].agg(
    average_interest_rate='mean'
).reset_index()

interest_by_status['average_interest_rate'] = (
    interest_by_status['average_interest_rate'].round(2)
)

interest_by_status

  loan_status  average_interest_rate
0      Active                  12.62
1      Closed                  12.60
2     Default                  12.40

In [52]:
# Default Rate by Interest Rate Band

loans['interest_rate_band'] = pd.cut(
    loans['interest_rate'],
    bins=[0, 10, 12, 14, 16, 20],
    labels=['Below 10%', '10%-12%', '12%-14%', '14%-16%', 'Above 16%']
)

default_by_rate_band = loans.groupby('interest_rate_band', observed=False).agg(
    total_loans=('loan_id', 'count'),
    defaulted_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

default_by_rate_band['default_rate'] = (
    default_by_rate_band['defaulted_loans'] /
    default_by_rate_band['total_loans'] * 100
).round(2)

default_by_rate_band

  interest_rate_band  total_loans  defaulted_loans  default_rate
0          Below 10%          502               54         10.76
1            10%-12%          380               38         10.00
2            12%-14%          359               25          6.96
3            14%-16%          411               37          9.00
4          Above 16%          348               36         10.34

In [53]:
# Customer-Level Loan Exposure Analysis

customer_loan_exposure = loans.groupby('customer_id').agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum')
).reset_index()

# Sort customers by total outstanding amount
customer_loan_exposure = customer_loan_exposure.sort_values(
    by='total_outstanding',
    ascending=False
)

# Display the top 10 customers
customer_loan_exposure.head(10)

     customer_id  total_loans  total_loan_amount  total_outstanding
1282      C17075            2       4,489,948.08       3,331,530.64
452       C12459            3       4,362,302.64       3,290,568.92
1420      C17823            2       4,244,754.30       3,143,483.98
1152      C16401            2       3,795,436.24       3,142,439.20
262       C11561            2       4,079,988.88       2,844,405.25
602       C13329            2       4,725,252.80       2,816,292.86
346       C11961            3       5,454,667.70       2,700,666.75
356       C12015            2       3,824,996.38       2,573,611.58
1495      C18197            2       3,420,513.82       2,454,792.59
117       C10716            2       4,094,105.07       2,451,419.78

In [54]:
from pathlib import Path

# Search the Desktop/AI folder for Loans.csv
search_folder = Path.home() / "Desktop" / "AI"

if search_folder.exists():
    matches = list(search_folder.rglob("Loans.csv"))
    matches += list(search_folder.rglob("loans.csv"))

    if matches:
        print("Dataset found!")
        for file in matches:
            print(file)
    else:
        print("Loans.csv was not found inside Desktop/AI.")
else:
    print("Desktop/AI folder not found.")
    print("Check the folder location:", Path.home() / "Desktop" / "AI")

Dataset found!
/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/data/Loans.csv
/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/data/loans.csv

In [55]:
import pandas as pd

# Load the existing loans dataset
loans = pd.read_csv(
    "/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/data/Loans.csv"
)

print("Loans dataset loaded successfully!")
print("Dataset shape:", loans.shape)
print("\nColumn names:")
print(loans.columns.tolist())

display(loans.head())

Loans dataset loaded successfully!
Dataset shape: (2000, 8)

Column names:
['loan_id', 'customer_id', 'loan_type', 'loan_amount', 'interest_rate', 'loan_date', 'loan_status', 'outstanding_amount']

,loan_id,customer_id,loan_type,loan_amount,interest_rate,loan_date,loan_status,outstanding_amount
0,L00001,C11825,Personal,"1,866,798.72",9.69,2024-05-22,Closed,"1,136,935.56"
1,L00002,C18936,Personal,"1,496,706.66",7.35,2024-04-05,Active,"680,731.76"
2,L00003,C10435,Business,"537,152.24",14.15,2025-07-12,Active,"217,164.28"
3,L00004,C14558,Personal,"1,909,078.05",8.76,2025-03-08,Active,"267,140.25"
4,L00005,C15515,Personal,"277,227.32",8.06,2024-12-18,Closed,"201,382.21"

In [56]:
# Multiple Loans per Customer Analysis

customer_loan_exposure = loans.groupby('customer_id').agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum')
).reset_index()

multiple_loan_customers = customer_loan_exposure[
    customer_loan_exposure['total_loans'] > 1
].copy()

multiple_loan_summary = pd.DataFrame({
    'Metric': [
        'Total Customers with Multiple Loans',
        'Total Loans Held by These Customers',
        'Total Loan Amount',
        'Total Outstanding Amount'
    ],
    'Value': [
        multiple_loan_customers['customer_id'].nunique(),
        multiple_loan_customers['total_loans'].sum(),
        multiple_loan_customers['total_loan_amount'].sum(),
        multiple_loan_customers['total_outstanding'].sum()
    ]
})

# Format output to display full numeric values
multiple_loan_summary['Value'] = multiple_loan_summary.apply(
    lambda row: f"{int(row['Value']):,}"
    if row['Metric'] in [
        'Total Customers with Multiple Loans',
        'Total Loans Held by These Customers'
    ]
    else f"{row['Value']:,.2f}",
    axis=1
)

display(multiple_loan_summary)

                                Metric           Value
0  Total Customers with Multiple Loans             178
1  Total Loans Held by These Customers             370
2                    Total Loan Amount  464,880,539.59
3             Total Outstanding Amount  215,773,838.13

In [58]:
# Customer Default Risk by Number of Loans

# Count loans for each customer
customer_loan_count = loans.groupby('customer_id').agg(
    total_loans=('loan_id', 'count')
).reset_index()

# Identify customers who have at least one defaulted loan
customer_default = loans.groupby('customer_id').agg(
    has_default=('loan_status', lambda x: (x == 'Default').any())
).reset_index()

# Combine loan count and default information
customer_risk = customer_loan_count.merge(
    customer_default,
    on='customer_id'
)

# Group customers by number of loans
customer_risk['loan_category'] = customer_risk['total_loans'].apply(
    lambda x: 'Single Loan' if x == 1 else 'Multiple Loans'
)

# Calculate default risk for each category
default_risk_by_loan_count = customer_risk.groupby('loan_category').agg(
    total_customers=('customer_id', 'count'),
    customers_with_default=('has_default', 'sum')
).reset_index()

# Calculate default rate
default_risk_by_loan_count['default_rate'] = (
    default_risk_by_loan_count['customers_with_default']
    / default_risk_by_loan_count['total_customers']
    * 100
)

# Display results
default_risk_by_loan_count

    loan_category  total_customers  customers_with_default  default_rate
0  Multiple Loans              178                      26         14.61
1     Single Loan             1630                     163         10.00

In [59]:
# Customer Default Risk by Outstanding Amount

# Step 1: Calculate total outstanding amount for each customer
customer_outstanding = loans.groupby('customer_id').agg(
    total_outstanding=('outstanding_amount', 'sum')
).reset_index()

# Step 2: Identify customers with at least one defaulted loan
customer_defaults = loans.groupby('customer_id').agg(
    has_default=('loan_status', lambda x: (x == 'Default').any())
).reset_index()

# Step 3: Combine outstanding amount and default information
customer_risk_outstanding = customer_outstanding.merge(
    customer_defaults,
    on='customer_id'
)

# Step 4: Divide customers into five groups based on outstanding amount
customer_risk_outstanding['outstanding_group'] = pd.qcut(
    customer_risk_outstanding['total_outstanding'],
    q=5,
    labels=['Very Low', 'Low', 'Medium', 'High', 'Very High'],
    duplicates='drop'
)

# Step 5: Calculate default rate for each group
default_by_outstanding = customer_risk_outstanding.groupby(
    'outstanding_group',
    observed=False
).agg(
    total_customers=('customer_id', 'count'),
    customers_with_default=('has_default', 'sum')
).reset_index()

# Step 6: Calculate default rate percentage
default_by_outstanding['default_rate'] = (
    default_by_outstanding['customers_with_default']
    / default_by_outstanding['total_customers']
    * 100
).round(2)

# Step 7: Display results
default_by_outstanding

  outstanding_group  total_customers  customers_with_default  default_rate
0          Very Low              362                      35          9.67
1               Low              361                      42         11.63
2            Medium              362                      37         10.22
3              High              361                      35          9.70
4         Very High              362                      40         11.05

In [60]:
import os
import pandas as pd

project_path = os.path.expanduser(
    "~/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence"
)

customers_path = os.path.join(
    project_path, "data", "customers.csv"
)

customers = pd.read_csv(customers_path)

print("Customers dataset loaded successfully!")
print("Shape:", customers.shape)
print("Columns:", customers.columns.tolist())

customers.head()

Customers dataset loaded successfully!
Shape: (10000, 7)
Columns: ['customer_id', 'age', 'gender', 'city', 'occupation', 'annual_income', 'customer_since']

,customer_id,age,gender,city,occupation,annual_income,customer_since
0,C10001,59,Male,Delhi,Teacher,418183,2015-02-21
1,C10002,49,Male,Kochi,Teacher,1585307,2010-07-08
2,C10003,35,Female,Kolkata,Other,833642,2013-12-11
3,C10004,63,Male,Coimbatore,Self Employed,1061744,2013-05-05
4,C10005,28,Male,Delhi,Self Employed,357764,2017-02-10

In [61]:
# Average Outstanding Loan Amount by Customer Income Group

customer_loan_income = loans.merge(
    customers[['customer_id', 'annual_income']],
    on='customer_id',
    how='left'
)

customer_income_outstanding = customer_loan_income.groupby(
    ['customer_id', 'annual_income']
).agg(
    total_outstanding=('outstanding_amount', 'sum')
).reset_index()

customer_income_outstanding['income_group'] = pd.qcut(
    customer_income_outstanding['annual_income'],
    q=5,
    labels=['Very Low', 'Low', 'Medium', 'High', 'Very High'],
    duplicates='drop'
)

outstanding_by_income = customer_income_outstanding.groupby(
    'income_group',
    observed=False
).agg(
    total_customers=('customer_id', 'count'),
    average_outstanding=('total_outstanding', 'mean'),
    total_outstanding=('total_outstanding', 'sum')
).reset_index()

display(outstanding_by_income.round(2))

  income_group  total_customers  average_outstanding  total_outstanding
0     Very Low              362           634,883.38     229,827,783.44
1          Low              361           633,074.59     228,539,927.03
2       Medium              362           590,368.19     213,713,284.59
3         High              361           581,635.39     209,970,376.64
4    Very High              362           702,372.04     254,258,677.65

In [62]:
# Average Loan Amount by Customer Income Group

customer_loan_amount = loans.merge(
    customers[['customer_id', 'annual_income']],
    on='customer_id',
    how='left'
)

# Create five income groups
customer_loan_amount['income_group'] = pd.qcut(
    customer_loan_amount['annual_income'],
    q=5,
    labels=['Very Low', 'Low', 'Medium', 'High', 'Very High']
)

# Calculate loan statistics for each income group
average_loan_by_income = customer_loan_amount.groupby(
    'income_group',
    observed=False
).agg(
    total_loans=('loan_id', 'count'),
    average_loan_amount=('loan_amount', 'mean'),
    total_loan_amount=('loan_amount', 'sum')
).reset_index()

# Format the results
average_loan_by_income[
    ['average_loan_amount', 'total_loan_amount']
] = average_loan_by_income[
    ['average_loan_amount', 'total_loan_amount']
].round(2)

# Display results
average_loan_by_income

  income_group  total_loans  average_loan_amount  total_loan_amount
0     Very Low          400         1,294,501.73     517,800,690.72
1          Low          400         1,296,141.77     518,456,707.73
2       Medium          400         1,196,918.88     478,767,551.56
3         High          400         1,246,331.25     498,532,501.01
4    Very High          400         1,277,167.95     510,867,179.63

In [63]:
# Audit the code cells in the current notebook

import json
from pathlib import Path

notebook_path = Path.cwd() / "Banking_Risk_Analysis.ipynb"

with open(notebook_path, "r", encoding="utf-8") as file:
    notebook = json.load(file)

for cell_number, cell in enumerate(notebook["cells"], start=1):
    if cell["cell_type"] == "code":
        source = "".join(cell["source"]).strip()

        if source:
            print(f"\n{'=' * 60}")
            print(f"CELL {cell_number}")
            print(source[:500])

============================================================
CELL 1
import pandas as pd

customers = pd.read_csv("../data/customers.csv")
accounts = pd.read_csv("../data/accounts.csv")
transactions = pd.read_csv("../data/Transactions.csv")
loans = pd.read_csv("../data/Loans.csv")

print("Customers:", customers.shape)
print("Accounts:", accounts.shape)
print("Transactions:", transactions.shape)
print("Loans:", loans.shape)

============================================================
CELL 2
print("CUSTOMERS")
print(customers.columns.tolist())

print("\nACCOUNTS")
print(accounts.columns.tolist())

print("\nTRANSACTIONS")
print(transactions.columns.tolist())

print("\nLOANS")
print(loans.columns.tolist())

============================================================
CELL 3
print("CUSTOMERS")
customers.info()

print("\nACCOUNTS")
accounts.info()

print("\nTRANSACTIONS")
transactions.info()

print("\nLOANS")
loans.info()

============================================================
CELL 4
customers["customer_since"] = pd.to_datetime(customers["customer_since"])
accounts["account_opening_date"] = pd.to_datetime(accounts["account_opening_date"])
transactions["transaction_date"] = pd.to_datetime(transactions["transaction_date"])
loans["loan_date"] = pd.to_datetime(loans["loan_date"])

print("Date conversion completed.")
print(customers["customer_since"].dtype)
print(accounts["account_opening_date"].dtype)
print(transactions["transaction_date"].dtype)
print(loans["loan_date"].dtype)

============================================================
CELL 5
print("Duplicate records:")
print("Customers:", customers.duplicated().sum())
print("Accounts:", accounts.duplicated().sum())
print("Transactions:", transactions.duplicated().sum())
print("Loans:", loans.duplicated().sum())

============================================================
CELL 6
print("Gender:")
print(customers["gender"].unique())

print("\nAccount Type:")
print(accounts["account_type"].unique())

print("\nAccount Status:")
print(accounts["status"].unique())

print("\nTransaction Type:")
print(transactions["transaction_type"].unique())

print("\nLoan Type:")
print(loans["loan_type"].unique())

print("\nLoan Status:")
print(loans["loan_status"].unique())

============================================================
CELL 7
customer_summary = customers[["age", "annual_income"]].describe()

print(customer_summary)

============================================================
CELL 8
occupation_summary = (
    customers["occupation"]
    .value_counts()
    .reset_index()
)

occupation_summary.columns = ["occupation", "customer_count"]

print(occupation_summary)

============================================================
CELL 9
#Loan portfolio by loan type

loan_type_summary = (
    loans.groupby("loan_type")
    .agg(
        total_loans=("loan_id", "count"),
        total_loan_amount=("loan_amount", "sum"),
        total_outstanding=("outstanding_amount", "sum")
    )
    .reset_index()
)

print(loan_type_summary)

#note:e+08 simply means × 100,000,000.

============================================================
CELL 10
pd.options.display.float_format = '{:,.2f}'.format

print(loan_type_summary)

============================================================
CELL 11
# Loan status analysis

loan_status_summary = (
    loans.groupby("loan_status")
    .agg(
        total_loans=("loan_id", "count"),
        total_loan_amount=("loan_amount", "sum"),
        total_outstanding=("outstanding_amount", "sum")
    )
    .reset_index()
)

print(loan_status_summary)

============================================================
CELL 12
#Calculate the overall default rate

total_loans = len(loans)
default_loans = (loans["loan_status"] == "Default").sum()

default_rate = (default_loans / total_loans) * 100

print(f"Total Loans: {total_loans:,}")
print(f"Default Loans: {default_loans:,}")
print(f"Default Rate: {default_rate:.2f}%")

============================================================
CELL 13
# Outstanding Amount by Loan Status

outstanding_by_status = loans.groupby('loan_status')['outstanding_amount'].agg(
    total_outstanding='sum',
    average_outstanding='mean'
).reset_index()

outstanding_by_status

============================================================
CELL 14
# Average Interest Rate by Loan Type

interest_by_type = loans.groupby('loan_type')['interest_rate'].agg(
    average_interest_rate='mean'
).reset_index()

interest_by_type

============================================================
CELL 15
# Total and Average Loan Amount by Loan Type

loan_amount_by_type = loans.groupby('loan_type')['loan_amount'].agg(
    total_loan_amount='sum',
    average_loan_amount='mean'
).reset_index()

loan_amount_by_type

============================================================
CELL 16
# Outstanding Amount by Loan Type

outstanding_by_type = loans.groupby('loan_type')['outstanding_amount'].agg(
    total_outstanding='sum',
    average_outstanding='mean'
).reset_index()

outstanding_by_type

============================================================
CELL 17
# Loan Status Distribution by Loan Type

loan_status_by_type = pd.crosstab(
    loans['loan_type'],
    loans['loan_status']
)

loan_status_by_type

============================================================
CELL 18
# Default Rate by Loan Type

default_rate_by_type = loans.groupby('loan_type').agg(
    total_loans=('loan_id', 'count'),
    defaulted_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

default_rate_by_type['default_rate'] = (
    default_rate_by_type['defaulted_loans'] /
    default_rate_by_type['total_loans'] * 100
)

default_rate_by_type

============================================================
CELL 19
# Interest Rate Distribution

interest_rate_summary = loans['interest_rate'].agg(
    minimum_rate='min',
    maximum_rate='max',
    average_rate='mean',
    median_rate='median'
)

interest_rate_summary

============================================================
CELL 20
# Average Interest Rate by Loan Status

interest_by_status = loans.groupby('loan_status')['interest_rate'].agg(
    average_interest_rate='mean'
).reset_index()

interest_by_status

============================================================
CELL 21
# Average Loan Amount by Loan Status

loan_amount_by_status = loans.groupby('loan_status')['loan_amount'].agg(
    total_loan_amount='sum',
    average_loan_amount='mean'
).reset_index()

loan_amount_by_status

============================================================
CELL 22
# Loan Amount Share by Loan Status

loan_amount_share = loans.groupby('loan_status')['loan_amount'].sum().reset_index()

total_loan_amount = loan_amount_share['loan_amount'].sum()

loan_amount_share['loan_amount_percentage'] = (
    loan_amount_share['loan_amount'] / total_loan_amount * 100
).round(2)

loan_amount_share

============================================================
CELL 23
# Outstanding Amount Share by Loan Status

outstanding_share = loans.groupby('loan_status')['outstanding_amount'].sum().reset_index()

total_outstanding = outstanding_share['outstanding_amount'].sum()

outstanding_share['outstanding_amount_percentage'] = (
    outstanding_share['outstanding_amount'] / total_outstanding * 100
).round(2)

outstanding_share

============================================================
CELL 24
# Outstanding Ratio by Loan Status

outstanding_ratio = loans.groupby('loan_status').agg(
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum')
).reset_index()

outstanding_ratio['outstanding_ratio'] = (
    outstanding_ratio['total_outstanding'] /
    outstanding_ratio['total_loan_amount'] * 100
).round(2)

outstanding_ratio

============================================================
CELL 25
# Loan Status Count by Loan Type

loan_status_by_type = pd.crosstab(
    loans['loan_type'],
    loans['loan_status']
)

loan_status_by_type

============================================================
CELL 26
# Loan Amount vs Outstanding Amount by Loan Type

loan_amount_vs_outstanding = loans.groupby('loan_type').agg(
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding_amount=('outstanding_amount', 'sum')
).reset_index()

loan_amount_vs_outstanding

============================================================
CELL 27
# Outstanding Ratio by Loan Type

outstanding_ratio_by_type = loans.groupby('loan_type').agg(
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding_amount=('outstanding_amount', 'sum')
).reset_index()

outstanding_ratio_by_type['outstanding_ratio'] = (
    outstanding_ratio_by_type['total_outstanding_amount'] /
    outstanding_ratio_by_type['total_loan_amount'] * 100
).round(2)

outstanding_ratio_by_type

============================================================
CELL 28
# Loan Amount by Loan Type and Status

loan_amount_type_status = pd.pivot_table(
    loans,
    values='loan_amount',
    index='loan_type',
    columns='loan_status',
    aggfunc='sum'
).round(2)

loan_amount_type_status

============================================================
CELL 29
# Outstanding Amount by Loan Type and Status

outstanding_type_status = pd.pivot_table(
    loans,
    values='outstanding_amount',
    index='loan_type',
    columns='loan_status',
    aggfunc='sum'
).round(2)

outstanding_type_status

============================================================
CELL 30
# Average Outstanding Amount by Loan Type

avg_outstanding_by_type = loans.groupby('loan_type')['outstanding_amount'].agg(
    average_outstanding_amount='mean'
).reset_index()

avg_outstanding_by_type

============================================================
CELL 31
# Default Outstanding Ratio by Loan Type

default_outstanding_ratio = loans.groupby('loan_type').agg(
    total_outstanding=('outstanding_amount', 'sum'),
    default_outstanding=('outstanding_amount',
                         lambda x: x[loans.loc[x.index, 'loan_status'] == 'Default'].sum())
).reset_index()

default_outstanding_ratio['default_outstanding_ratio'] = (
    default_outstanding_ratio['default_outstanding'] /
    default_outstanding_ratio['total_outstanding'] * 100
).round(2)

defaul

============================================================
CELL 32
# Average Defaulted Loan Amount by Loan Type

avg_default_loan = loans[loans['loan_status'] == 'Default'].groupby(
    'loan_type'
)['loan_amount'].agg(
    default_loan_count='count',
    average_default_loan_amount='mean'
).reset_index()

avg_default_loan['average_default_loan_amount'] = (
    avg_default_loan['average_default_loan_amount'].round(2)
)

avg_default_loan

============================================================
CELL 33
# Average Outstanding Amount for Defaulted Loans by Loan Type

avg_default_outstanding = loans[
    loans['loan_status'] == 'Default'
].groupby('loan_type')['outstanding_amount'].agg(
    default_loan_count='count',
    average_default_outstanding='mean'
).reset_index()

avg_default_outstanding['average_default_outstanding'] = (
    avg_default_outstanding['average_default_outstanding'].round(2)
)

avg_default_outstanding

============================================================
CELL 34
# Average Loan Amount by Loan Type

average_loan_by_type = loans.groupby('loan_type')['loan_amount'].agg(
    total_loans='count',
    average_loan_amount='mean'
).reset_index()

average_loan_by_type

============================================================
CELL 35
# Default Rate by Interest Rate Group

loans['interest_rate_group'] = pd.cut(
    loans['interest_rate'],
    bins=[0, 8, 10, 12, 14, 16, 20],
    labels=['<=8%', '8-10%', '10-12%', '12-14%', '14-16%', '>16%']
)

interest_risk = loans.groupby('interest_rate_group', observed=True).agg(
    total_loans=('loan_id', 'count'),
    default_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

interest_risk['default_rate'] = (
    interest_risk['default_loans'] /
    interest_risk['t

============================================================
CELL 36
# Default Rate by Loan Amount Group

loans['loan_amount_group'] = pd.qcut(
    loans['loan_amount'],
    q=5,
    labels=['Very Low', 'Low', 'Medium', 'High', 'Very High']
)

loan_amount_risk = loans.groupby('loan_amount_group', observed=True).agg(
    total_loans=('loan_id', 'count'),
    default_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

loan_amount_risk['default_rate'] = (
    loan_amount_risk['default_loans'] /
    loan_amount_risk['total_loans'] * 100
).round(2

============================================================
CELL 37
customers = pd.read_csv('../Data/customers.csv')

customers.head()

============================================================
CELL 38
# Default Rate by Customer Income Group

loans_income = loans.merge(
    customers[['customer_id', 'annual_income']],
    on='customer_id',
    how='left'
)

loans_income['income_group'] = pd.qcut(
    loans_income['annual_income'],
    q=5,
    labels=['Very Low', 'Low', 'Medium', 'High', 'Very High']
)

income_risk = loans_income.groupby('income_group', observed=True).agg(
    total_loans=('loan_id', 'count'),
    default_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()


============================================================
CELL 39
# Loan-to-Income Ratio and Default Risk

loans_income['loan_to_income_ratio'] = (
    loans_income['loan_amount'] / loans_income['annual_income']
)

loans_income['loan_to_income_group'] = pd.qcut(
    loans_income['loan_to_income_ratio'],
    q=5,
    labels=['Very Low', 'Low', 'Medium', 'High', 'Very High']
)

loan_income_risk = loans_income.groupby(
    'loan_to_income_group',
    observed=True
).agg(
    total_loans=('loan_id', 'count'),
    default_loans=('loan_status', lambda x: (x == 'Defa

============================================================
CELL 40
# Customer Loan Exposure and Default Risk

customer_exposure = loans.groupby('customer_id').agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum'),
    default_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

customer_exposure['default_rate'] = (
    customer_exposure['default_loans'] /
    customer_exposure['total_loans'] * 100
).round(2)

customer_exposure.sort_values(
    'total_loan_

============================================================
CELL 41
# Loan Status Distribution by Loan Type

loan_type_status = pd.crosstab(
    loans['loan_type'],
    loans['loan_status']
).reset_index()

loan_type_status

============================================================
CELL 42
# Outstanding Exposure by Loan Status

outstanding_by_status = loans.groupby('loan_status').agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum'),
    average_outstanding=('outstanding_amount', 'mean')
).reset_index()

outstanding_by_status

============================================================
CELL 43
# Outstanding Amount as % of Original Loan Amount

loans['outstanding_ratio'] = (
    loans['outstanding_amount'] / loans['loan_amount'] * 100
)

loans['outstanding_ratio'].describe()

============================================================
CELL 44
# Average Outstanding Ratio by Loan Type

outstanding_ratio_by_type = loans.groupby('loan_type')['outstanding_ratio'].agg(
    average_outstanding_ratio='mean'
).reset_index()

outstanding_ratio_by_type['average_outstanding_ratio'] = (
    outstanding_ratio_by_type['average_outstanding_ratio'] * 100
).round(2)

outstanding_ratio_by_type

============================================================
CELL 45
# Average Outstanding Ratio by Loan Status

outstanding_ratio_by_status = loans.groupby('loan_status')['outstanding_ratio'].agg(
    average_outstanding_ratio='mean'
).reset_index()

outstanding_ratio_by_status['average_outstanding_ratio'] = (
    outstanding_ratio_by_status['average_outstanding_ratio'] * 100
).round(2)

outstanding_ratio_by_status

============================================================
CELL 46
# Outstanding Amount Ratio by Loan Type

outstanding_amount_ratio = loans.groupby('loan_type').agg(
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding_amount=('outstanding_amount', 'sum')
).reset_index()

outstanding_amount_ratio['outstanding_amount_ratio'] = (
    outstanding_amount_ratio['total_outstanding_amount'] /
    outstanding_amount_ratio['total_loan_amount'] * 100
).round(2)

outstanding_amount_ratio

============================================================
CELL 47
# Average Interest Rate by Loan Status

interest_by_status = loans.groupby('loan_status')['interest_rate'].agg(
    average_interest_rate='mean'
).reset_index()

interest_by_status['average_interest_rate'] = (
    interest_by_status['average_interest_rate'].round(2)
)

interest_by_status

============================================================
CELL 48
# Default Rate by Interest Rate Band

loans['interest_rate_band'] = pd.cut(
    loans['interest_rate'],
    bins=[0, 10, 12, 14, 16, 20],
    labels=['Below 10%', '10%-12%', '12%-14%', '14%-16%', 'Above 16%']
)

default_by_rate_band = loans.groupby('interest_rate_band', observed=False).agg(
    total_loans=('loan_id', 'count'),
    defaulted_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

default_by_rate_band['default_rate'] = (
    default_by_rate_band['defaulted_loans'

============================================================
CELL 49
# Customer-Level Loan Exposure Analysis

customer_loan_exposure = loans.groupby('customer_id').agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum')
).reset_index()

# Sort customers by total outstanding amount
customer_loan_exposure = customer_loan_exposure.sort_values(
    by='total_outstanding',
    ascending=False
)

# Display the top 10 customers
customer_loan_exposure.head(10)

============================================================
CELL 50
from pathlib import Path

# Search the Desktop/AI folder for Loans.csv
search_folder = Path.home() / "Desktop" / "AI"

if search_folder.exists():
    matches = list(search_folder.rglob("Loans.csv"))
    matches += list(search_folder.rglob("loans.csv"))

    if matches:
        print("Dataset found!")
        for file in matches:
            print(file)
    else:
        print("Loans.csv was not found inside Desktop/AI.")
else:
    print("Desktop/AI folder not found.")
    print("Check the folder

============================================================
CELL 51
import pandas as pd

# Load the existing loans dataset
loans = pd.read_csv(
    "/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/data/Loans.csv"
)

print("Loans dataset loaded successfully!")
print("Dataset shape:", loans.shape)
print("\nColumn names:")
print(loans.columns.tolist())

display(loans.head())

============================================================
CELL 52
# Multiple Loans per Customer Analysis

customer_loan_exposure = loans.groupby('customer_id').agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum')
).reset_index()

multiple_loan_customers = customer_loan_exposure[
    customer_loan_exposure['total_loans'] > 1
].copy()

multiple_loan_summary = pd.DataFrame({
    'Metric': [
        'Total Customers with Multiple Loans',
        'Total Loans Held by These Custo

============================================================
CELL 53
# Customer Loan Outstanding Ratio Analysis

customer_outstanding_ratio = loans.groupby('customer_id').agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum')
).reset_index()


In [64]:
import pandas as pd

# Load all four datasets
customers = pd.read_csv("../data/customers.csv")
accounts = pd.read_csv("../data/accounts.csv")
transactions = pd.read_csv("../data/Transactions.csv")
loans = pd.read_csv("../data/Loans.csv")

print("All datasets loaded successfully!")
print("-" * 40)

print("Customers:", customers.shape)
print("Accounts:", accounts.shape)
print("Transactions:", transactions.shape)
print("Loans:", loans.shape)

All datasets loaded successfully!
----------------------------------------
Customers: (10000, 7)
Accounts: (13000, 6)
Transactions: (5000, 6)
Loans: (2000, 8)

In [65]:
# Check columns in all four datasets

print("CUSTOMERS COLUMNS")
print(customers.columns.tolist())

print("\nACCOUNTS COLUMNS")
print(accounts.columns.tolist())

print("\nTRANSACTIONS COLUMNS")
print(transactions.columns.tolist())

print("\nLOANS COLUMNS")
print(loans.columns.tolist())

CUSTOMERS COLUMNS
['customer_id', 'age', 'gender', 'city', 'occupation', 'annual_income', 'customer_since']

ACCOUNTS COLUMNS
['account_id', 'customer_id', 'account_type', 'balance', 'account_opening_date', 'status']

TRANSACTIONS COLUMNS
['transaction_id', 'account_id', 'transaction_date', 'transaction_type', 'amount', 'balance_after_transaction']

LOANS COLUMNS
['loan_id', 'customer_id', 'loan_type', 'loan_amount', 'interest_rate', 'loan_date', 'loan_status', 'outstanding_amount']

In [66]:
# Transaction Analysis by Transaction Type

transaction_analysis = transactions.groupby('transaction_type').agg(
    total_transactions=('transaction_id', 'count'),
    total_amount=('amount', 'sum'),
    average_amount=('amount', 'mean'),
    minimum_amount=('amount', 'min'),
    maximum_amount=('amount', 'max')
).reset_index()

# Round monetary values to two decimal places
transaction_analysis[
    ['total_amount', 'average_amount', 'minimum_amount', 'maximum_amount']
] = transaction_analysis[
    ['total_amount', 'average_amount', 'minimum_amount', 'maximum_amount']
].round(2)

# Sort by transaction volume
transaction_analysis = transaction_analysis.sort_values(
    by='total_transactions',
    ascending=False
)

print("TRANSACTION ANALYSIS BY TRANSACTION TYPE")
display(transaction_analysis)

TRANSACTION ANALYSIS BY TRANSACTION TYPE

,transaction_type,total_transactions,total_amount,average_amount,minimum_amount,maximum_amount
2,Transfer,1694,"42,142,944.11","24,877.77",104.27,"49,949.45"
0,Credit,1658,"41,348,941.37","24,939.05",117.13,"49,975.18"
1,Debit,1648,"41,063,204.31","24,916.99",172.88,"49,898.38"

In [16]:
display(transaction_analysis)

,transaction_type,total_transactions,total_amount,average_amount,minimum_amount,maximum_amount
2,Transfer,1694,42142944.11,24877.77,104.27,49949.45
0,Credit,1658,41348941.37,24939.05,117.13,49975.18
1,Debit,1648,41063204.31,24916.99,172.88,49898.38

In [67]:
# Monthly Transaction Trend Analysis

# Convert transaction_date to datetime
transactions['transaction_date'] = pd.to_datetime(
    transactions['transaction_date']
)

# Extract year and month
transactions['transaction_month'] = (
    transactions['transaction_date'].dt.to_period('M')
)

# Aggregate monthly transaction statistics
monthly_transactions = transactions.groupby(
    'transaction_month'
).agg(
    total_transactions=('transaction_id', 'count'),
    total_amount=('amount', 'sum'),
    average_amount=('amount', 'mean')
).reset_index()

# Format monetary values
monthly_transactions[
    ['total_amount', 'average_amount']
] = monthly_transactions[
    ['total_amount', 'average_amount']
].round(2)

print("MONTHLY TRANSACTION TREND")
display(monthly_transactions)

MONTHLY TRANSACTION TREND

   transaction_month  total_transactions  total_amount  average_amount
0            2025-01                 399 10,118,051.87       25,358.53
1            2025-02                 386  9,862,009.65       25,549.25
2            2025-03                 432 11,057,732.99       25,596.60
3            2025-04                 419 10,448,160.59       24,935.94
4            2025-05                 433 10,409,404.02       24,040.19
5            2025-06                 398  9,524,607.52       23,931.17
6            2025-07                 426 10,721,616.54       25,168.11
7            2025-08                 434 10,531,905.00       24,267.06
8            2025-09                 396  9,967,042.66       25,169.30
9            2025-10                 444 10,501,889.18       23,652.90
10           2025-11                 406 10,447,055.28       25,731.66
11           2025-12                 427 10,965,614.49       25,680.60

In [68]:
import pandas as pd

# Load all four datasets

customers = pd.read_csv("../data/customers.csv")

accounts = pd.read_csv("../data/accounts.csv")

transactions = pd.read_csv("../data/Transactions.csv")

loans = pd.read_csv("../data/Loans.csv")

print("Pandas imported and all datasets loaded successfully!")

Pandas imported and all datasets loaded successfully!

In [70]:
# Customer Default Risk by Number of Loans

# Step 1: Count loans and identify customers with defaults
customer_loan_risk = loans.groupby('customer_id').agg(
    total_loans=('loan_id', 'count'),
    has_default=('loan_status', lambda x: (x == 'Default').any())
).reset_index()

# Step 2: Categorize customers by number of loans
customer_loan_risk['loan_category'] = customer_loan_risk[
    'total_loans'
].apply(
    lambda x: 'Single Loan' if x == 1 else 'Multiple Loans'
)

# Step 3: Calculate default risk by loan category
default_risk_by_loan_count = customer_loan_risk.groupby(
    'loan_category'
).agg(
    total_customers=('customer_id', 'count'),
    customers_with_default=('has_default', 'sum')
).reset_index()

# Step 4: Calculate default rate
default_risk_by_loan_count['default_rate'] = (
    default_risk_by_loan_count['customers_with_default']
    / default_risk_by_loan_count['total_customers']
) * 100

# Step 5: Display results
default_risk_by_loan_count['default_rate'] = (
    default_risk_by_loan_count['default_rate'].round(2)
)

print("Customer Default Risk by Number of Loans")
display(default_risk_by_loan_count)

Customer Default Risk by Number of Loans

    loan_category  total_customers  customers_with_default  default_rate
0  Multiple Loans              178                      26         14.61
1     Single Loan             1630                     163         10.00

In [2]:
import pandas as pd

# Reload the banking datasets
customers = pd.read_csv("../data/customers.csv")
accounts = pd.read_csv("../data/accounts.csv")
transactions = pd.read_csv("../data/Transactions.csv")
loans = pd.read_csv("../data/Loans.csv")

print("Customers:", customers.shape)
print("Accounts:", accounts.shape)
print("Transactions:", transactions.shape)
print("Loans:", loans.shape)

print("\nAll datasets loaded successfully!")

Customers: (10000, 7)
Accounts: (13000, 6)
Transactions: (5000, 6)
Loans: (2000, 8)

All datasets loaded successfully!

In [4]:
# Customer Loan Outstanding Analysis by Age Group

import pandas as pd

# Step 1: Merge customers and loans
customer_loans = pd.merge(
    customers,
    loans,
    on='customer_id',
    how='inner'
)

# Step 2: Create age groups
customer_loans['age_group'] = pd.cut(
    customer_loans['age'],
    bins=[0, 25, 35, 45, 55, 100],
    labels=[
        'Below 25',
        '25-35',
        '36-45',
        '46-55',
        'Above 55'
    ],
    right=True
)

# Step 3: Calculate outstanding amounts by age group
age_outstanding = customer_loans.groupby(
    'age_group',
    observed=False
).agg(
    total_customers=('customer_id', 'nunique'),
    total_outstanding=('outstanding_amount', 'sum'),
    average_outstanding_per_loan=('outstanding_amount', 'mean')
).reset_index()

# Step 4: Calculate customer-level default rates
customer_default = customer_loans.groupby(
    ['age_group', 'customer_id'],
    observed=False
).agg(
    has_default=('loan_status', lambda x: (x == 'Default').any())
).reset_index()

default_by_age = customer_default.groupby(
    'age_group',
    observed=False
).agg(
    customers_with_default=('has_default', 'sum')
).reset_index()

# Step 5: Merge results
age_outstanding = age_outstanding.merge(
    default_by_age,
    on='age_group',
    how='left'
)

# Step 6: Calculate customer default rate
age_outstanding['default_rate'] = (
        age_outstanding['customers_with_default']
        / age_outstanding['total_customers']
        * 100
).fillna(0).round(2)

# Step 7: Round monetary values
age_outstanding['total_outstanding'] = (
    age_outstanding['total_outstanding'].round(2)
)

age_outstanding['average_outstanding_per_loan'] = (
    age_outstanding['average_outstanding_per_loan'].round(2)
)

print("Customer Loan Outstanding Analysis by Age Group")
display(age_outstanding)

Customer Loan Outstanding Analysis by Age Group

,age_group,total_customers,total_outstanding,average_outstanding_per_loan,customers_with_default,default_rate
0,Below 25,193,1.354777e+08,618619.74,18,9.33
1,25-35,397,2.273213e+08,528654.22,33,8.31
2,36-45,382,2.405005e+08,564555.22,42,10.99
3,46-55,424,2.730462e+08,578487.68,58,13.68
4,Above 55,412,2.599643e+08,573872.63,38,9.22

In [5]:
# Display the complete age-group analysis

display(age_outstanding.to_string(index=False))

'age_group  total_customers  total_outstanding  average_outstanding_per_loan  customers_with_default  default_rate\n Below 25              193       135477723.61                     618619.74                      18          9.33\n    25-35              397       227321316.73                     528654.22                      33          8.31\n    36-45              382       240500524.84                     564555.22                      42         10.99\n    46-55              424       273046183.19                     578487.68                      58         13.68\n Above 55              412       259964300.98                     573872.63                      38          9.22'

In [6]:
import pandas as pd

# Step 1: Calculate customer-level loan metrics
customer_risk = loans.groupby('customer_id').agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum'),
    defaulted_loans=('loan_status', lambda x: (x == 'Default').sum())
).reset_index()

# Step 2: Calculate outstanding ratio
customer_risk['outstanding_ratio'] = (
                                             customer_risk['total_outstanding']
                                             / customer_risk['total_loan_amount']
                                     ) * 100

# Step 3: Calculate whether a customer has at least one defaulted loan
customer_risk['has_default'] = (
        customer_risk['defaulted_loans'] > 0
)

# Step 4: Merge customer information
customer_risk = customer_risk.merge(
    customers[['customer_id', 'age', 'annual_income', 'occupation']],
    on='customer_id',
    how='left'
)

# Step 5: Display customers with the highest outstanding ratios
customer_risk = customer_risk.sort_values(
    'outstanding_ratio',
    ascending=False
)

print("Customer-Level Risk Analysis")
display(customer_risk.head(10).round(2))

Customer-Level Risk Analysis

,customer_id,total_loans,total_loan_amount,total_outstanding,defaulted_loans,outstanding_ratio,has_default,age,annual_income,occupation
1154,C16409,1,1942238.47,1743998.95,0,89.79,False,24,624339,Healthcare Professional
625,C13472,1,359155.70,322357.43,0,89.75,False,52,2173490,Government Employee
1279,C17060,1,2232165.83,2002941.48,0,89.73,False,58,2385379,Consultant
92,C10563,1,834341.43,748540.88,0,89.72,False,41,1796666,Private Employee
1579,C18658,1,2286806.40,2049182.10,0,89.61,False,47,1572887,Teacher
437,C12390,1,1208818.21,1083107.88,0,89.60,False,52,735237,IT Professional
1792,C19909,1,1096281.33,981743.94,0,89.55,False,44,388989,Consultant
62,C10381,1,1974126.64,1766510.97,1,89.48,True,43,1273831,Healthcare Professional
962,C15306,1,1134213.33,1013317.02,0,89.34,False,46,897073,Engineer
1762,C19759,1,2423855.29,2165296.08,0,89.33,False,40,922547,Consultant

In [7]:
# Transaction Analysis by Transaction Type

print("Transaction Dataset Columns:")
print(transactions.columns.tolist())

print("\nTransaction Types:")
print(transactions["transaction_type"].value_counts(dropna=False))

transaction_type_analysis = (
    transactions.groupby("transaction_type", dropna=False)
    .agg(
        total_transactions=("amount", "count"),
        total_transaction_amount=("amount", "sum"),
        average_transaction_amount=("amount", "mean")
    )
    .reset_index()
)

transaction_type_analysis["total_transaction_amount"] = (
    transaction_type_analysis["total_transaction_amount"].round(2)
)

transaction_type_analysis["average_transaction_amount"] = (
    transaction_type_analysis["average_transaction_amount"].round(2)
)

print("\nTransaction Analysis by Type:")
print(transaction_type_analysis.to_string(index=False))

Transaction Dataset Columns:
['transaction_id', 'account_id', 'transaction_date', 'transaction_type', 'amount', 'balance_after_transaction']

Transaction Types:
transaction_type
Transfer    1694
Credit      1658
Debit       1648
Name: count, dtype: int64

Transaction Analysis by Type:
transaction_type  total_transactions  total_transaction_amount  average_transaction_amount
          Credit                1658               41348941.37                    24939.05
           Debit                1648               41063204.31                    24916.99
        Transfer                1694               42142944.11                    24877.77

In [8]:
print(transaction_type_analysis.to_string(index=False))

transaction_type  total_transactions  total_transaction_amount  average_transaction_amount
          Credit                1658               41348941.37                    24939.05
           Debit                1648               41063204.31                    24916.99
        Transfer                1694               42142944.11                    24877.77

In [9]:
# Check transaction date range and missing values

print("TRANSACTION DATE RANGE")
print("Start Date:", transactions["transaction_date"].min())
print("End Date:", transactions["transaction_date"].max())

print("\nMISSING VALUES")
print(transactions.isnull().sum())

print("\nDUPLICATE TRANSACTION IDs")
print(transactions["transaction_id"].duplicated().sum())

TRANSACTION DATE RANGE
Start Date: 2025-01-01
End Date: 2025-12-31

MISSING VALUES
transaction_id               0
account_id                   0
transaction_date             0
transaction_type             0
amount                       0
balance_after_transaction    0
dtype: int64

DUPLICATE TRANSACTION IDs
0

In [10]:
print(
    "Duplicate Transaction IDs:",
    transactions["transaction_id"].duplicated().sum()
)

Duplicate Transaction IDs: 0

In [11]:
# Monthly transaction analysis

transactions["transaction_date"] = pd.to_datetime(
    transactions["transaction_date"]
)

transactions["transaction_month"] = (
    transactions["transaction_date"].dt.to_period("M")
)

monthly_transaction_analysis = (
    transactions.groupby("transaction_month")
    .agg(
        total_transactions=("transaction_id", "count"),
        total_amount=("amount", "sum"),
        average_amount=("amount", "mean")
    )
    .reset_index()
)

print(monthly_transaction_analysis.to_string(index=False))
print("\nTotal months:", len(monthly_transaction_analysis))

transaction_month  total_transactions  total_amount  average_amount
          2025-01                 399   10118051.87    25358.525990
          2025-02                 386    9862009.65    25549.247798
          2025-03                 432   11057732.99    25596.604144
          2025-04                 419   10448160.59    24935.944129
          2025-05                 433   10409404.02    24040.194042
          2025-06                 398    9524607.52    23931.174673
          2025-07                 426   10721616.54    25168.113944
          2025-08                 434   10531905.00    24267.062212
          2025-09                 396    9967042.66    25169.299646
          2025-10                 444   10501889.18    23652.903559
          2025-11                 406   10447055.28    25731.663251
          2025-12                 427   10965614.49    25680.595995

Total months: 12

In [12]:
print("JULY TO DECEMBER 2025")
print(monthly_transaction_analysis.tail(6).to_string(index=False))

print("\nTotal months:", len(monthly_transaction_analysis))
print(
    "Total transactions:",
    monthly_transaction_analysis["total_transactions"].sum()
)

JULY TO DECEMBER 2025
transaction_month  total_transactions  total_amount  average_amount
          2025-07                 426   10721616.54    25168.113944
          2025-08                 434   10531905.00    24267.062212
          2025-09                 396    9967042.66    25169.299646
          2025-10                 444   10501889.18    23652.903559
          2025-11                 406   10447055.28    25731.663251
          2025-12                 427   10965614.49    25680.595995

Total months: 12
Total transactions: 5000

In [13]:
# Check the key columns used to connect the datasets

print("CUSTOMERS")
print(customers.columns.tolist())

print("\nACCOUNTS")
print(accounts.columns.tolist())

print("\nTRANSACTIONS")
print(transactions.columns.tolist())

print("\nLOANS")
print(loans.columns.tolist())

CUSTOMERS
['customer_id', 'age', 'gender', 'city', 'occupation', 'annual_income', 'customer_since']

ACCOUNTS
['account_id', 'customer_id', 'account_type', 'balance', 'account_opening_date', 'status']

TRANSACTIONS
['transaction_id', 'account_id', 'transaction_date', 'transaction_type', 'amount', 'balance_after_transaction', 'transaction_month']

LOANS
['loan_id', 'customer_id', 'loan_type', 'loan_amount', 'interest_rate', 'loan_date', 'loan_status', 'outstanding_amount']

In [14]:
print("LOANS")
print(loans.columns.tolist())

LOANS
['loan_id', 'customer_id', 'loan_type', 'loan_amount', 'interest_rate', 'loan_date', 'loan_status', 'outstanding_amount']

In [15]:
import pandas as pd

loans = pd.read_csv("../data/Loans.csv")

print("Loans shape:", loans.shape)
print("Loans columns:", loans.columns.tolist())

Loans shape: (2000, 8)
Loans columns: ['loan_id', 'customer_id', 'loan_type', 'loan_amount', 'interest_rate', 'loan_date', 'loan_status', 'outstanding_amount']

In [16]:
# Analyze default risk by loan amount

loans['loan_amount_group'] = pd.cut(
    loans['loan_amount'],
    bins=5,
    precision=0
)

loan_amount_risk = loans.groupby(
    'loan_amount_group',
    observed=False
).agg(
    total_loans=('loan_id', 'count'),
    defaulted_loans=(
        'loan_status',
        lambda x: (x == 'Default').sum()
    ),
    total_loan_amount=('loan_amount', 'sum'),
    average_loan_amount=('loan_amount', 'mean'),
    total_outstanding=('outstanding_amount', 'sum')
).reset_index()

loan_amount_risk['default_rate'] = (
    loan_amount_risk['defaulted_loans']
    / loan_amount_risk['total_loans']
    * 100
).round(2)

loan_amount_risk['total_loan_amount'] = (
    loan_amount_risk['total_loan_amount'].round(2)
)

loan_amount_risk['average_loan_amount'] = (
    loan_amount_risk['average_loan_amount'].round(2)
)

loan_amount_risk['total_outstanding'] = (
    loan_amount_risk['total_outstanding'].round(2)
)

print(loan_amount_risk.to_string(index=False))

     loan_amount_group  total_loans  defaulted_loans  total_loan_amount  average_loan_amount  total_outstanding  default_rate
   (48418.0, 540549.0]          437               44       134232808.67            307168.90        61547897.77         10.07
 (540549.0, 1030232.0]          381               34       294814949.02            773792.52       139092412.84          8.92
(1030232.0, 1519915.0]          379               39       484196830.74           1277564.20       216135879.91         10.29
(1519915.0, 2009598.0]          396               34       694755301.81           1754432.58       315768831.96          8.59
(2009598.0, 2499281.0]          407               39       916424740.41           2251657.84       403765026.87          9.58

In [17]:
# Interest Rate and Outstanding Amount by Loan Status

interest_outstanding_analysis = loans.groupby(
    'loan_status'
).agg(
    total_loans=('loan_id', 'count'),
    average_interest_rate=('interest_rate', 'mean'),
    average_loan_amount=('loan_amount', 'mean'),
    average_outstanding=('outstanding_amount', 'mean'),
    total_outstanding=('outstanding_amount', 'sum')
).round(2).reset_index()

print(interest_outstanding_analysis.to_string(index=False))

loan_status  total_loans  average_interest_rate  average_loan_amount  average_outstanding  total_outstanding
     Active         1214                  12.62           1262110.34            575157.11       698240731.73
     Closed          596                  12.60           1260335.85            551837.87       328895370.00
    Default          190                  12.40           1268750.04            574599.72       109173947.62

In [18]:
# Calculate outstanding ratio for each loan

loans['outstanding_ratio'] = (
    loans['outstanding_amount']
    / loans['loan_amount']
) * 100

# Analyze outstanding ratio by loan status

outstanding_ratio_status = loans.groupby(
    'loan_status'
).agg(
    total_loans=('loan_id', 'count'),
    average_loan_amount=('loan_amount', 'mean'),
    average_outstanding=('outstanding_amount', 'mean'),
    average_outstanding_ratio=('outstanding_ratio', 'mean'),
    median_outstanding_ratio=('outstanding_ratio', 'median')
).round(2).reset_index()

print(outstanding_ratio_status.to_string(index=False))

loan_status  total_loans  average_loan_amount  average_outstanding  average_outstanding_ratio  median_outstanding_ratio
     Active         1214           1262110.34            575157.11                      45.89                     45.89
     Closed          596           1260335.85            551837.87                      44.33                     44.17
    Default          190           1268750.04            574599.72                      45.27                     49.16

In [19]:
# Investigate outstanding balances for closed loans

closed_loans = loans[
    loans['loan_status'] == 'Closed'
].copy()

print("Total closed loans:", len(closed_loans))

print(
    "Closed loans with zero outstanding:",
    (closed_loans['outstanding_amount'] == 0).sum()
)

print(
    "Closed loans with positive outstanding:",
    (closed_loans['outstanding_amount'] > 0).sum()
)

print(
    "Closed loans with negative outstanding:",
    (closed_loans['outstanding_amount'] < 0).sum()
)

print(
    "\nOutstanding balance statistics for closed loans:"
)

print(
    closed_loans['outstanding_amount'].describe().round(2)
)

Total closed loans: 596
Closed loans with zero outstanding: 0
Closed loans with positive outstanding: 596
Closed loans with negative outstanding: 0

Outstanding balance statistics for closed loans:
count        596.00
mean      551837.87
std       472291.26
min         2504.12
25%       157345.07
50%       439430.68
75%       827129.06
max      2145114.75
Name: outstanding_amount, dtype: float64

In [20]:
# Check outstanding amount and ratio by loan status

loans['outstanding_ratio'] = (
    loans['outstanding_amount']
    / loans['loan_amount']
) * 100

status_check = loans.groupby('loan_status').agg(
    total_loans=('loan_id', 'count'),
    zero_outstanding=(
        'outstanding_amount',
        lambda x: (x == 0).sum()
    ),
    positive_outstanding=(
        'outstanding_amount',
        lambda x: (x > 0).sum()
    ),
    average_outstanding=('outstanding_amount', 'mean'),
    average_outstanding_ratio=('outstanding_ratio', 'mean'),
    minimum_outstanding=('outstanding_amount', 'min'),
    maximum_outstanding=('outstanding_amount', 'max')
).round(2).reset_index()

print(status_check.to_string(index=False))

loan_status  total_loans  zero_outstanding  positive_outstanding  average_outstanding  average_outstanding_ratio  minimum_outstanding  maximum_outstanding
     Active         1214                 0                  1214            575157.11                      45.89                65.04           2165296.08
     Closed          596                 0                   596            551837.87                      44.33              2504.12           2145114.75
    Default          190                 0                   190            574599.72                      45.27              6492.98           2130263.46

In [21]:
# Validate outstanding amounts against original loan amounts

loans['outstanding_ratio'] = (
    loans['outstanding_amount']
    / loans['loan_amount']
) * 100

print(
    "Outstanding greater than original loan:",
    (loans['outstanding_amount'] > loans['loan_amount']).sum()
)

print(
    "Outstanding equal to original loan:",
    (loans['outstanding_amount'] == loans['loan_amount']).sum()
)

print(
    "Outstanding less than original loan:",
    (loans['outstanding_amount'] < loans['loan_amount']).sum()
)

print("\nOutstanding ratio statistics:")

print(
    loans['outstanding_ratio']
    .describe()
    .round(2)
)

Outstanding greater than original loan: 0
Outstanding equal to original loan: 0
Outstanding less than original loan: 2000

Outstanding ratio statistics:
count    2000.00
mean       45.37
std        25.75
min         0.00
25%        23.35
50%        45.75
75%        67.43
max        89.91
Name: outstanding_ratio, dtype: float64

In [22]:
# Analyze default risk by number of loans per customer

customer_loan_summary = loans.groupby('customer_id').agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum'),
    defaulted_loans=(
        'loan_status',
        lambda x: (x == 'Default').sum()
    )
).reset_index()

# Categorize customers by number of loans

customer_loan_summary['loan_count_group'] = pd.cut(
    customer_loan_summary['total_loans'],
    bins=[0, 1, 2, float('inf')],
    labels=['1 Loan', '2 Loans', '3+ Loans']
)

# Summarize customer-level risk

multiple_loan_analysis = customer_loan_summary.groupby(
    'loan_count_group',
    observed=False
).agg(
    total_customers=('customer_id', 'count'),
    total_loans=('total_loans', 'sum'),
    customers_with_default=(
        'defaulted_loans',
        lambda x: (x > 0).sum()
    ),
    total_outstanding=('total_outstanding', 'sum')
).reset_index()

multiple_loan_analysis['customer_default_rate'] = (
    multiple_loan_analysis['customers_with_default']
    / multiple_loan_analysis['total_customers']
    * 100
).round(2)

print(multiple_loan_analysis.to_string(index=False))

loan_count_group  total_customers  total_loans  customers_with_default  total_outstanding  customer_default_rate
          1 Loan             1630         1630                     163       920536211.22                  10.00
         2 Loans              166          332                      23       197126020.82                  13.86
        3+ Loans               12           38                       3        18647817.31                  25.00

In [23]:
# Validate loan-level and customer-level default counts

defaulted_loans = loans[
    loans['loan_status'] == 'Default'
]

print("Total loans:", len(loans))

print("Total defaulted loans:", len(defaulted_loans))

print(
    "Distinct customers with defaulted loans:",
    defaulted_loans['customer_id'].nunique()
)

print(
    "Customers with multiple defaulted loans:",
    (
        defaulted_loans['customer_id']
        .value_counts() > 1
    ).sum()
)

print(
    "\nCustomers with multiple loans:",
    (loans.groupby('customer_id').size() > 1).sum()
)

Total loans: 2000
Total defaulted loans: 190
Distinct customers with defaulted loans: 189
Customers with multiple defaulted loans: 1

Customers with multiple loans: 178

In [24]:
# Identify customers with the highest total outstanding loan amounts

customer_exposure = loans.groupby('customer_id').agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum'),
    defaulted_loans=(
        'loan_status',
        lambda x: (x == 'Default').sum()
    )
).reset_index()

# Calculate combined outstanding ratio

customer_exposure['outstanding_ratio'] = (
    customer_exposure['total_outstanding']
    / customer_exposure['total_loan_amount']
    * 100
).round(2)

# Sort customers by total outstanding amount

top_customer_exposure = customer_exposure.sort_values(
    'total_outstanding',
    ascending=False
).head(10)

print(top_customer_exposure.to_string(index=False))

customer_id  total_loans  total_loan_amount  total_outstanding  defaulted_loans  outstanding_ratio
     C17075            2         4489948.08         3331530.64                0              74.20
     C12459            3         4362302.64         3290568.92                1              75.43
     C17823            2         4244754.30         3143483.98                0              74.06
     C16401            2         3795436.24         3142439.20                0              82.80
     C11561            2         4079988.88         2844405.25                1              69.72
     C13329            2         4725252.80         2816292.86                0              59.60
     C11961            3         5454667.70         2700666.75                0              49.51
     C12015            2         3824996.38         2573611.58                0              67.28
     C18197            2         3420513.82         2454792.59                0              71.77
     C10716            2         4094105.07         2451419.78                0              59.88

In [25]:
# Merge loan information with customer income

customer_loan_risk = loans.merge(
    customers[['customer_id', 'annual_income']],
    on='customer_id',
    how='left'
)

# Calculate total loans, loan amount, and outstanding amount
customer_loan_risk = customer_loan_risk.groupby(
    'customer_id'
).agg(
    total_loans=('loan_id', 'count'),
    total_loan_amount=('loan_amount', 'sum'),
    total_outstanding=('outstanding_amount', 'sum'),
    annual_income=('annual_income', 'first'),
    defaulted_loans=(
        'loan_status',
        lambda x: (x == 'Default').sum()
    )
).reset_index()

# Keep customers with multiple loans
customer_loan_risk = customer_loan_risk[
    customer_loan_risk['total_loans'] > 1
].copy()

# Calculate outstanding debt as a percentage of annual income
customer_loan_risk['outstanding_to_income_ratio'] = (
    customer_loan_risk['total_outstanding']
    / customer_loan_risk['annual_income']
) * 100

# Display the top 10 customers
top_debt_burden = customer_loan_risk.sort_values(
    'outstanding_to_income_ratio',
    ascending=False
).head(10)

print(top_debt_burden.round(2).to_string(index=False))

customer_id  total_loans  total_loan_amount  total_outstanding  annual_income  defaulted_loans  outstanding_to_income_ratio
     C16401            2         3795436.24         3142439.20         346780                0                       906.18
     C12015            2         3824996.38         2573611.58         293235                0                       877.66
     C12589            2         2300707.40         1704459.97         259757                0                       656.17
     C14537            2         4112789.56         2218082.34         340630                0                       651.17
     C16533            2         3602846.74         1761968.80         272901                0                       645.64
     C18737            2         2235290.43         1790626.89         295649                0                       605.66
     C17192            2         2785401.28         2305394.00         388210                0                       593.85
     C11961            3         5454667.70         2700666.75         469546                0                       575.17
     C10686            2         2418680.34         2068705.44         377277                0                       548.33
     C15645            2         3576852.95         2105449.77         430429                1                       489.15

In [26]:
# Create debt burden categories

customer_loan_risk['debt_burden_group'] = pd.cut(
    customer_loan_risk['outstanding_to_income_ratio'],
    bins=[0, 100, 200, 400, float('inf')],
    labels=[
        'Below 100%',
        '100%-200%',
        '200%-400%',
        'Above 400%'
    ],
    right=False
)

# Summarize default risk by debt burden group

debt_burden_analysis = customer_loan_risk.groupby(
    'debt_burden_group',
    observed=False
).agg(
    total_customers=('customer_id', 'count'),
    customers_with_default=(
        'defaulted_loans',
        lambda x: (x > 0).sum()
    ),
    total_loans=('total_loans', 'sum'),
    total_outstanding=('total_outstanding', 'sum')
).reset_index()

# Calculate customer default rate

debt_burden_analysis['customer_default_rate'] = (
    debt_burden_analysis['customers_with_default']
    / debt_burden_analysis['total_customers']
) * 100

print(debt_burden_analysis.round(2).to_string(index=False))

debt_burden_group  total_customers  customers_with_default  total_loans  total_outstanding  customer_default_rate
       Below 100%              110                      16          226        92829243.64                  14.55
        100%-200%               47                       4          100        81284256.10                   8.51
        200%-400%               10                       5           21        17517007.29                  50.00
       Above 400%               11                       1           23        24143331.10                   9.09

In [27]:
# Group customers by number of loans

loan_count_risk = customer_loan_risk.groupby(
    'total_loans'
).agg(
    total_customers=('customer_id', 'count'),
    customers_with_default=(
        'defaulted_loans',
        lambda x: (x > 0).sum()
    ),
    total_outstanding=('total_outstanding', 'sum')
).reset_index()

# Calculate customer default rate

loan_count_risk['customer_default_rate'] = (
    loan_count_risk['customers_with_default']
    / loan_count_risk['total_customers']
) * 100

print(loan_count_risk.round(2).to_string(index=False))

 total_loans  total_customers  customers_with_default  total_outstanding  customer_default_rate
           2              166                      23       197126020.82                  13.86
           3               10                       3        15873682.28                  30.00
           4                2                       0         2774135.03                   0.00

In [28]:
# Total number of customers with at least one defaulted loan

total_customers_with_default = loans.loc[
    loans['loan_status'] == 'Default',
    'customer_id'
].nunique()

# Total number of defaulted loans
total_defaulted_loans = (
    loans['loan_status'] == 'Default'
).sum()

print("Total loans:", len(loans))
print("Total defaulted loans:", total_defaulted_loans)
print(
    "Distinct customers with defaults:",
    total_customers_with_default
)

Total loans: 2000
Total defaulted loans: 190
Distinct customers with defaults: 189

In [6]:
import os

project_path = "/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence"

for root, dirs, files in os.walk(project_path):
    for file in files:
        if file.lower() in ["loans.csv", "customers.csv", "accounts.csv", "transactions.csv"]:
            print(os.path.join(root, file))

/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/data/customers.csv
/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/data/accounts.csv
/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/data/Loans.csv
/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/data/Transactions.csv

In [4]:
# ============================================================
# BANKING CUSTOMER RISK & LOAN INTELLIGENCE
# FINAL LOAN DEFAULT PREDICTION MODEL
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

# ------------------------------------------------------------
# 1. PREPARE DATA
# ------------------------------------------------------------

data = ml_data.copy()

# Keep only legitimate target values
data = data[data["default_flag"].isin([0, 1])].copy()
data["default_flag"] = data["default_flag"].astype(int)

# Use only features available for risk assessment.
# Exclude loan_status, IDs, and dates to prevent leakage.
features = [
    "loan_type",
    "loan_amount",
    "interest_rate",
    "age",
    "gender",
    "occupation",
    "annual_income"
]

X = data[features].copy()
y = data["default_flag"]

numeric_features = [
    "loan_amount",
    "interest_rate",
    "age",
    "annual_income"
]

categorical_features = [
    "loan_type",
    "gender",
    "occupation"
]

print("Dataset shape:", data.shape)
print("Total loans:", len(data))
print("Defaulted loans:", int(y.sum()))
print("Default rate:", round(y.mean() * 100, 2), "%")

# ------------------------------------------------------------
# 2. PREPROCESSING
# ------------------------------------------------------------

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

# ------------------------------------------------------------
# 3. SPLIT DATA
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# ------------------------------------------------------------
# 4. TRAIN RANDOM FOREST
# ------------------------------------------------------------

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=500,
        max_depth=5,
        min_samples_leaf=10,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ))
])

model.fit(X_train, y_train)

# ------------------------------------------------------------
# 5. EVALUATE ON UNSEEN TEST DATA
# ------------------------------------------------------------

probabilities = model.predict_proba(X_test)[:, 1]

# Default threshold: 0.50
predictions = (probabilities >= 0.50).astype(int)

print("\n" + "=" * 60)
print("FINAL MODEL EVALUATION")
print("=" * 60)

print("ROC-AUC:",
      round(roc_auc_score(y_test, probabilities), 4))

print("Average Precision:",
      round(average_precision_score(y_test, probabilities), 4))

print("\nClassification Report:")
print(classification_report(
    y_test,
    predictions,
    labels=[0, 1],
    target_names=["Non-Default", "Default"],
    zero_division=0
))

print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions))

# ------------------------------------------------------------
# 6. CROSS-VALIDATION ON TRAINING DATA
# ------------------------------------------------------------

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

cv_results = cross_validate(
    model,
    X_train,
    y_train,
    cv=cv,
    scoring={
        "roc_auc": "roc_auc",
        "average_precision": "average_precision",
        "recall": "recall"
    },
    n_jobs=1
)

print("\n" + "=" * 60)
print("5-FOLD CROSS-VALIDATION")
print("=" * 60)

print(
    "Mean ROC-AUC:",
    round(cv_results["test_roc_auc"].mean(), 4)
)

print(
    "Mean Average Precision:",
    round(cv_results["test_average_precision"].mean(), 4)
)

print(
    "Mean Recall:",
    round(cv_results["test_recall"].mean(), 4)
)

# ------------------------------------------------------------
# 7. CONFUSION MATRIX VISUALIZATION
# ------------------------------------------------------------

ConfusionMatrixDisplay.from_predictions(
    y_test,
    predictions,
    labels=[0, 1],
    display_labels=["Non-Default", "Default"]
)

plt.title("Loan Default Prediction - Random Forest")
plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 8. SAVE THE TRAINED MODEL
# ------------------------------------------------------------

joblib.dump(
    model,
    "banking_loan_default_model.pkl"
)

print("\nModel saved as banking_loan_default_model.pkl")

print("\nImportant:")
print("This model uses the existing synthetic default labels.")
print("Its predictive performance must be judged from the")
print("test results and cross-validation above.")

NameError: name 'ml_data' is not defined

In [5]:
# Check which datasets already exist
print([name for name in globals() if "loan" in name.lower() or "data" in name.lower()])

[]

In [6]:
import os

print("Current folder:", os.getcwd())
print("\nCSV files in current folder:")

for file in os.listdir():
    if file.endswith(".csv"):
        print(file)

Current folder: /Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/notebook

CSV files in current folder:

In [7]:
import os

project_folder = os.path.dirname(os.getcwd())

print("Searching project folder:", project_folder)
print("\nCSV files found:")

for root, dirs, files in os.walk(project_folder):
    dirs[:] = [d for d in dirs if d not in [".git", ".ipynb_checkpoints"]]

    for file in files:
        if file.lower().endswith(".csv"):
            print(os.path.join(root, file))

Searching project folder: /Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence

CSV files found:
/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/data/customers.csv
/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/data/accounts.csv
/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/data/Loans.csv
/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/data/Transactions.csv

In [8]:
import pandas as pd
import os

project_folder = os.path.dirname(os.getcwd())
data_folder = os.path.join(project_folder, "data")

loans = pd.read_csv(os.path.join(data_folder, "Loans.csv"))
customers = pd.read_csv(os.path.join(data_folder, "customers.csv"))

print("LOANS DATA")
print("Shape:", loans.shape)
print("Columns:", loans.columns.tolist())
print("\nFirst 3 rows:")
display(loans.head(3))

print("\nCUSTOMERS DATA")
print("Shape:", customers.shape)
print("Columns:", customers.columns.tolist())

LOANS DATA
Shape: (2000, 8)
Columns: ['loan_id', 'customer_id', 'loan_type', 'loan_amount', 'interest_rate', 'loan_date', 'loan_status', 'outstanding_amount']

First 3 rows:

,loan_id,customer_id,loan_type,loan_amount,interest_rate,loan_date,loan_status,outstanding_amount
0,L00001,C11825,Personal,1866798.72,9.69,2024-05-22,Closed,1136935.56
1,L00002,C18936,Personal,1496706.66,7.35,2024-04-05,Active,680731.76
2,L00003,C10435,Business,537152.24,14.15,2025-07-12,Active,217164.28

CUSTOMERS DATA
Shape: (10000, 7)
Columns: ['customer_id', 'age', 'gender', 'city', 'occupation', 'annual_income', 'customer_since']

In [9]:
print("Loan dataset shape:", loans.shape)
print("Loan columns:", loans.columns.tolist())
print("\nLoan status counts:")
print(loans["loan_status"].value_counts())

Loan dataset shape: (2000, 8)
Loan columns: ['loan_id', 'customer_id', 'loan_type', 'loan_amount', 'interest_rate', 'loan_date', 'loan_status', 'outstanding_amount']

Loan status counts:
loan_status
Active     1214
Closed      596
Default     190
Name: count, dtype: int64

In [10]:
import pandas as pd
import os

# Locate existing project data
project_folder = os.path.dirname(os.getcwd())
data_folder = os.path.join(project_folder, "data")

# Load existing datasets
loans = pd.read_csv(os.path.join(data_folder, "Loans.csv"))
customers = pd.read_csv(os.path.join(data_folder, "customers.csv"))

# Create the target variable
loans["default_flag"] = (loans["loan_status"] == "Default").astype(int)

# Combine loan and customer information
ml_data = loans.merge(
    customers,
    on="customer_id",
    how="left",
    validate="many_to_one"
)

# Display results
print("ML dataset shape:", ml_data.shape)
print("\nDefault flag distribution:")
print(ml_data["default_flag"].value_counts())

print("\nDefault rate:", round(ml_data["default_flag"].mean() * 100, 2), "%")
print("\nAvailable features:")
print(ml_data.columns.tolist())

display(ml_data.head())

ML dataset shape: (2000, 15)

Default flag distribution:
default_flag
0    1810
1     190
Name: count, dtype: int64

Default rate: 9.5 %

Available features:
['loan_id', 'customer_id', 'loan_type', 'loan_amount', 'interest_rate', 'loan_date', 'loan_status', 'outstanding_amount', 'default_flag', 'age', 'gender', 'city', 'occupation', 'annual_income', 'customer_since']

,loan_id,customer_id,loan_type,loan_amount,interest_rate,loan_date,loan_status,outstanding_amount,default_flag,age,gender,city,occupation,annual_income,customer_since
0,L00001,C11825,Personal,1866798.72,9.69,2024-05-22,Closed,1136935.56,0,23,Male,Coimbatore,Self Employed,1933083,2016-10-25
1,L00002,C18936,Personal,1496706.66,7.35,2024-04-05,Active,680731.76,0,55,Female,Chennai,Business Owner,278701,2018-02-10
2,L00003,C10435,Business,537152.24,14.15,2025-07-12,Active,217164.28,0,42,Male,Mumbai,Healthcare Professional,516983,2024-03-29
3,L00004,C14558,Personal,1909078.05,8.76,2025-03-08,Active,267140.25,0,63,Female,Hyderabad,Engineer,965252,2015-03-25
4,L00005,C15515,Personal,277227.32,8.06,2024-12-18,Closed,201382.21,0,27,Male,Chennai,Self Employed,1727837,2025-03-12

In [11]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    average_precision_score
)

# 1. Select predictors and target
target = "default_flag"

features = [
    "loan_type",
    "loan_amount",
    "interest_rate",
    "outstanding_amount",
    "age",
    "gender",
    "city",
    "occupation",
    "annual_income"
]

X = ml_data[features].copy()
y = ml_data[target].copy()

# 2. Identify numeric and categorical columns
numeric_features = X.select_dtypes(include=["number"]).columns.tolist()
categorical_features = X.select_dtypes(exclude=["number"]).columns.tolist()

# 3. Prepare preprocessing
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

# 4. Split data while preserving the default proportion
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# 5. Build the model
model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=300,
        max_depth=6,
        min_samples_leaf=10,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ))
])

# 6. Train once
model.fit(X_train, y_train)

# 7. Evaluate on the untouched test set
predictions = model.predict(X_test)
probabilities = model.predict_proba(X_test)[:, 1]

print("=" * 55)
print("BANKING LOAN DEFAULT PREDICTION MODEL")
print("=" * 55)

print(f"Training records: {len(X_train)}")
print(f"Testing records:  {len(X_test)}")
print(f"Test defaults:    {int(y_test.sum())}")
print(f"Test non-defaults: {int((y_test == 0).sum())}")

print(f"\nAccuracy: {accuracy_score(y_test, predictions):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, probabilities):.4f}")
print(f"Average precision: {average_precision_score(y_test, probabilities):.4f}")

print("\nClassification Report:")
print(classification_report(
    y_test,
    predictions,
    target_names=["Non-default", "Default"],
    zero_division=0
))

print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions))

=======================================================
BANKING LOAN DEFAULT PREDICTION MODEL
=======================================================
Training records: 1600
Testing records:  400
Test defaults:    38
Test non-defaults: 362

Accuracy: 0.7400
ROC-AUC: 0.5531
Average precision: 0.1336

Classification Report:
              precision    recall  f1-score   support

 Non-default       0.92      0.78      0.84       362
     Default       0.14      0.34      0.20        38

    accuracy                           0.74       400
   macro avg       0.53      0.56      0.52       400
weighted avg       0.84      0.74      0.78       400

Confusion Matrix:
[[283  79]
 [ 25  13]]

In [12]:
# ================================================================
# BANKING CUSTOMER RISK & LOAN INTELLIGENCE
# COMPLETE MACHINE LEARNING PIPELINE
# ================================================================

import os
import json
import warnings
import joblib
import numpy as np
import pandas as pd

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    cross_val_score
)
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

warnings.filterwarnings("ignore")

# ------------------------------------------------
# 1. FIND PROJECT AND LOAD EXISTING DATA
# ------------------------------------------------

possible_roots = [
    os.path.dirname(os.getcwd()),
    os.getcwd(),
    os.path.expanduser(
        "~/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence"
    )
]

PROJECT = None

for root in possible_roots:
    if os.path.exists(os.path.join(root, "data", "Loans.csv")):
        PROJECT = root
        break

if PROJECT is None:
    raise FileNotFoundError(
        "Could not locate data/Loans.csv. "
        "Please run this cell from your existing project notebook."
    )

DATA = os.path.join(PROJECT, "data")
OUTPUT = os.path.join(PROJECT, "ml_results")
os.makedirs(OUTPUT, exist_ok=True)

loans = pd.read_csv(os.path.join(DATA, "Loans.csv"))
customers = pd.read_csv(os.path.join(DATA, "customers.csv"))

print("=" * 65)
print("BANKING CUSTOMER RISK & LOAN INTELLIGENCE")
print("=" * 65)
print("Project:", PROJECT)
print("Loans:", loans.shape)
print("Customers:", customers.shape)

# ------------------------------------------------
# 2. VALIDATE AND PREPARE TARGET
# ------------------------------------------------

required_loan_columns = [
    "loan_id", "customer_id", "loan_type", "loan_amount",
    "interest_rate", "loan_date", "loan_status",
    "outstanding_amount"
]

missing = set(required_loan_columns) - set(loans.columns)

if missing:
    raise ValueError(f"Missing required loan columns: {sorted(missing)}")

if loans["loan_id"].duplicated().any():
    raise ValueError("Duplicate loan IDs detected. Investigate before training.")

loans["loan_status"] = loans["loan_status"].astype(str).str.strip()

# Closed and Active loans are treated as non-defaults.
# Default loans are the positive class.
loans = loans[loans["loan_status"].isin(
    ["Active", "Closed", "Default"]
)].copy()

loans["default_flag"] = (
    loans["loan_status"] == "Default"
).astype(int)

if loans["default_flag"].nunique() != 2:
    raise ValueError("The target must contain both default classes.")

customers = customers.drop_duplicates("customer_id")

data = loans.merge(
    customers,
    on="customer_id",
    how="left",
    validate="many_to_one"
)

print("\nTarget distribution:")
print(data["loan_status"].value_counts())
print(f"Overall default rate: {data['default_flag'].mean():.2%}")

# ------------------------------------------------
# 3. FEATURE ENGINEERING
# ------------------------------------------------

# Parse dates and calculate elapsed time.
data["loan_date"] = pd.to_datetime(data["loan_date"], errors="coerce")
data["customer_since"] = pd.to_datetime(
    data["customer_since"], errors="coerce"
)

data["loan_year"] = data["loan_date"].dt.year
data["loan_month"] = data["loan_date"].dt.month

data["customer_tenure_years"] = (
    (data["loan_date"] - data["customer_since"]).dt.days / 365.25
).clip(lower=0)

# Financial ratios.
# These are candidate predictors, not guaranteed signals of default.
data["loan_to_income"] = (
    data["loan_amount"] /
    data["annual_income"].where(data["annual_income"] > 0)
)

data["outstanding_to_income"] = (
    data["outstanding_amount"] /
    data["annual_income"].where(data["annual_income"] > 0)
)

data["outstanding_to_loan"] = (
    data["outstanding_amount"] /
    data["loan_amount"].where(data["loan_amount"] > 0)
)

# Remove invalid numeric values.
data.replace([np.inf, -np.inf], np.nan, inplace=True)

# ------------------------------------------------
# 4. DEFINE PREDICTORS
# ------------------------------------------------

# Exclude identifiers, the target, and loan_status to prevent leakage.
# Note: outstanding_amount may reflect loan repayment progress.
# Its suitability depends on when the prediction is intended to occur.
features = [
    "loan_type",
    "loan_amount",
    "interest_rate",
    "age",
    "gender",
    "city",
    "occupation",
    "annual_income",
    "customer_tenure_years",
    "loan_to_income",
    "outstanding_to_income",
    "outstanding_to_loan",
    "loan_year",
    "loan_month"
]

X = data[features].copy()
y = data["default_flag"].copy()

numeric_features = X.select_dtypes(include=["number"]).columns.tolist()
categorical_features = [
    col for col in X.columns if col not in numeric_features
]

# ------------------------------------------------
# 5. STRATIFIED TRAIN/TEST SPLIT
# ------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining rows:", len(X_train))
print("Testing rows:", len(X_test))
print("Defaults in test set:", int(y_test.sum()))

# ------------------------------------------------
# 6. PREPROCESSING
# ------------------------------------------------

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

# ------------------------------------------------
# 7. COMPARE MODELS USING TRAINING DATA ONLY
# ------------------------------------------------

candidates = {
    "Logistic Regression": LogisticRegression(
        class_weight="balanced",
        max_iter=2000,
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        max_depth=6,
        min_samples_leaf=10,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ),

    "Extra Trees": ExtraTreesClassifier(
        n_estimators=300,
        max_depth=6,
        min_samples_leaf=10,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    )
}

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

results = []
pipelines = {}

print("\nComparing models with 5-fold cross-validation...")

for name, estimator in candidates.items():
    pipe = Pipeline([
        ("preprocessor", preprocessor),
        ("classifier", estimator)
    ])

    scores = cross_val_score(
        pipe,
        X_train,
        y_train,
        cv=cv,
        scoring="roc_auc",
        n_jobs=1
    )

    pipelines[name] = pipe

    results.append({
        "Model": name,
        "Mean_CV_ROC_AUC": scores.mean(),
        "CV_Std": scores.std()
    })

comparison = pd.DataFrame(results).sort_values(
    "Mean_CV_ROC_AUC",
    ascending=False
).reset_index(drop=True)

print("\nCROSS-VALIDATION RESULTS")
print(comparison.to_string(index=False))

# ------------------------------------------------
# 8. TRAIN SELECTED MODEL
# ------------------------------------------------

best_name = comparison.loc[0, "Model"]
best_model = pipelines[best_name]

best_model.fit(X_train, y_train)

probabilities = best_model.predict_proba(X_test)[:, 1]

# Standard threshold: 0.50.
# Do not tune using the test set.
predictions = (probabilities >= 0.50).astype(int)

# ------------------------------------------------
# 9. FINAL EVALUATION
# ------------------------------------------------

metrics = {
    "selected_model": best_name,
    "accuracy": float(accuracy_score(y_test, predictions)),
    "roc_auc": float(roc_auc_score(y_test, probabilities)),
    "average_precision": float(
        average_precision_score(y_test, probabilities)
    ),
    "default_precision": float(
        precision_score(y_test, predictions, zero_division=0)
    ),
    "default_recall": float(
        recall_score(y_test, predictions, zero_division=0)
    ),
    "default_f1": float(
        f1_score(y_test, predictions, zero_division=0)
    ),
    "test_records": int(len(y_test)),
    "test_defaults": int(y_test.sum()),
    "threshold": 0.50
}

print("\n" + "=" * 65)
print("FINAL TEST RESULTS")
print("=" * 65)

for key, value in metrics.items():
    if isinstance(value, float):
        print(f"{key}: {value:.4f}")
    else:
        print(f"{key}: {value}")

print("\nCLASSIFICATION REPORT")
print(classification_report(
    y_test,
    predictions,
    labels=[0, 1],
    target_names=["Non-default", "Default"],
    zero_division=0
))

cm = confusion_matrix(y_test, predictions, labels=[0, 1])

print("CONFUSION MATRIX")
print(pd.DataFrame(
    cm,
    index=["Actual Non-default", "Actual Default"],
    columns=["Predicted Non-default", "Predicted Default"]
))

# ------------------------------------------------
# 10. FEATURE IMPORTANCE
# ------------------------------------------------

# Permutation importance evaluates how much test ROC-AUC changes
# when a feature is shuffled. It is diagnostic, not causal evidence.
from sklearn.inspection import permutation_importance

permutation = permutation_importance(
    best_model,
    X_test,
    y_test,
    scoring="roc_auc",
    n_repeats=10,
    random_state=42,
    n_jobs=-1
)

importance = pd.DataFrame({
    "Feature": X_test.columns,
    "Importance_Mean": permutation.importances_mean,
    "Importance_Std": permutation.importances_std
}).sort_values("Importance_Mean", ascending=False)

print("\nTOP FEATURES BY PERMUTATION IMPORTANCE")
print(importance.head(10).to_string(index=False))

# ------------------------------------------------
# 11. SAVE MODEL AND RESULTS
# ------------------------------------------------

joblib.dump(
    best_model,
    os.path.join(OUTPUT, "banking_default_model.joblib")
)

comparison.to_csv(
    os.path.join(OUTPUT, "model_comparison.csv"),
    index=False
)

importance.to_csv(
    os.path.join(OUTPUT, "feature_importance.csv"),
    index=False
)

with open(
    os.path.join(OUTPUT, "evaluation_metrics.json"),
    "w"
) as f:
    json.dump(metrics, f, indent=4)

test_results = pd.DataFrame({
    "actual_default": y_test.to_numpy(),
    "predicted_default": predictions,
    "predicted_default_probability": probabilities
})

test_results.to_csv(
    os.path.join(OUTPUT, "test_predictions.csv"),
    index=False
)

print("\n" + "=" * 65)
print("PIPELINE COMPLETED")
print("=" * 65)
print("Saved model and reports to:", OUTPUT)
print("1. banking_default_model.joblib")
print("2. model_comparison.csv")
print("3. feature_importance.csv")
print("4. evaluation_metrics.json")
print("5. test_predictions.csv")

=================================================================
BANKING CUSTOMER RISK & LOAN INTELLIGENCE
=================================================================
Project: /Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence
Loans: (2000, 8)
Customers: (10000, 7)

Target distribution:
loan_status
Active     1214
Closed      596
Default     190
Name: count, dtype: int64
Overall default rate: 9.50%

Training rows: 1600
Testing rows: 400
Defaults in test set: 38

Comparing models with 5-fold cross-validation...

CROSS-VALIDATION RESULTS
              Model  Mean_CV_ROC_AUC   CV_Std
Logistic Regression         0.503878 0.024531
      Random Forest         0.485895 0.028625
        Extra Trees         0.475414 0.033439

=================================================================
FINAL TEST RESULTS
=================================================================
selected_model: Logistic Regression
accuracy: 0.5075
roc_auc: 0.5161
average_precision: 0.1052
default_precision: 0.1045
default_recall: 0.5526
default_f1: 0.1757
test_records: 400
test_defaults: 38
threshold: 0.5000

CLASSIFICATION REPORT
              precision    recall  f1-score   support

 Non-default       0.91      0.50      0.65       362
     Default       0.10      0.55      0.18        38

    accuracy                           0.51       400
   macro avg       0.51      0.53      0.41       400
weighted avg       0.84      0.51      0.60       400

CONFUSION MATRIX
                    Predicted Non-default  Predicted Default
Actual Non-default                    182                180
Actual Default                         17                 21

TOP FEATURES BY PERMUTATION IMPORTANCE
              Feature  Importance_Mean  Importance_Std
                 city         0.016931        0.024365
customer_tenure_years         0.011871        0.011277
                  age         0.007735        0.003177
           occupation         0.005954        0.023686
outstanding_to_income         0.004740        0.004710
          loan_amount         0.002137        0.007037
            loan_year         0.000487        0.000727
               gender        -0.000167        0.000581
           loan_month        -0.001265        0.004303
            loan_type        -0.001614        0.008960

=================================================================
PIPELINE COMPLETED
=================================================================
Saved model and reports to: /Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/ml_results
1. banking_default_model.joblib
2. model_comparison.csv
3. feature_importance.csv
4. evaluation_metrics.json
5. test_predictions.csv

In [13]:
# ============================================================
# FINAL MODEL EXPERIMENT: BANKING LOAN DEFAULT PREDICTION
# Reuses the existing ml_data dataframe
# ============================================================

import os
import joblib
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (
    RandomForestClassifier,
    ExtraTreesClassifier,
    HistGradientBoostingClassifier,
    GradientBoostingClassifier
)
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# 1. Prepare target
data = ml_data.copy()
data = data[data["loan_status"].isin(["Active", "Closed", "Default"])].copy()
data["default_flag"] = (data["loan_status"] == "Default").astype(int)

# 2. Create features available from loan/customer records
data["loan_date"] = pd.to_datetime(data["loan_date"], errors="coerce")
data["customer_since"] = pd.to_datetime(data["customer_since"], errors="coerce")

data["customer_tenure_years"] = (
    (data["loan_date"] - data["customer_since"]).dt.days / 365.25
).clip(lower=0)

data["loan_to_income"] = (
    data["loan_amount"] / data["annual_income"].where(data["annual_income"] > 0)
)

data["interest_to_income"] = (
    data["loan_amount"] * data["interest_rate"] / 100
) / data["annual_income"].where(data["annual_income"] > 0)

data["loan_year"] = data["loan_date"].dt.year
data["loan_month"] = data["loan_date"].dt.month

# Exclude outstanding_amount to avoid potential post-origination leakage.
features = [
    "loan_type",
    "loan_amount",
    "interest_rate",
    "age",
    "gender",
    "city",
    "occupation",
    "annual_income",
    "customer_tenure_years",
    "loan_to_income",
    "interest_to_income",
    "loan_year",
    "loan_month"
]

X = data[features].replace([np.inf, -np.inf], np.nan)
y = data["default_flag"]

numeric = X.select_dtypes(include="number").columns.tolist()
categorical = [c for c in X.columns if c not in numeric]

# 3. One fixed stratified test set
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

preprocessor = ColumnTransformer([
    ("num", Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scale", StandardScaler())
    ]), numeric),
    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encode", OneHotEncoder(handle_unknown="ignore"))
    ]), categorical)
])

# 4. Compare candidate algorithms using training data only
models = {
    "Logistic Regression": LogisticRegression(
        max_iter=3000, class_weight="balanced", random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=400, max_depth=6, min_samples_leaf=10,
        class_weight="balanced", random_state=42, n_jobs=-1
    ),
    "Extra Trees": ExtraTreesClassifier(
        n_estimators=400, max_depth=6, min_samples_leaf=10,
        class_weight="balanced", random_state=42, n_jobs=-1
    ),
    "Gradient Boosting": GradientBoostingClassifier(
        n_estimators=100, learning_rate=0.03,
        max_depth=2, random_state=42
    )
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
pipelines = {}
cv_results = []

for name, estimator in models.items():
    pipe = Pipeline([
        ("prep", preprocessor),
        ("model", estimator)
    ])

    scores = cross_val_score(
        pipe, X_train, y_train,
        scoring="roc_auc", cv=cv, n_jobs=1
    )

    pipelines[name] = pipe
    cv_results.append({
        "Model": name,
        "CV_ROC_AUC_Mean": scores.mean(),
        "CV_ROC_AUC_Std": scores.std()
    })

comparison = pd.DataFrame(cv_results).sort_values(
    "CV_ROC_AUC_Mean", ascending=False
).reset_index(drop=True)

print("\nCROSS-VALIDATED MODEL COMPARISON")
print(comparison.to_string(index=False))

# 5. Fit the best model according to cross-validation
best_name = comparison.iloc[0]["Model"]
best_model = pipelines[best_name]
best_model.fit(X_train, y_train)

prob = best_model.predict_proba(X_test)[:, 1]
pred = (prob >= 0.50).astype(int)

print("\nSELECTED MODEL:", best_name)
print("Test accuracy:", round(accuracy_score(y_test, pred), 4))
print("Balanced accuracy:", round(balanced_accuracy_score(y_test, pred), 4))
print("Test ROC-AUC:", round(roc_auc_score(y_test, prob), 4))
print("Average precision:", round(average_precision_score(y_test, prob), 4))
print("Default precision:", round(precision_score(y_test, pred, zero_division=0), 4))
print("Default recall:", round(recall_score(y_test, pred, zero_division=0), 4))
print("Default F1:", round(f1_score(y_test, pred, zero_division=0), 4))

print("\nCLASSIFICATION REPORT")
print(classification_report(
    y_test, pred,
    labels=[0, 1],
    target_names=["Non-default", "Default"],
    zero_division=0
))

print("CONFUSION MATRIX")
print(confusion_matrix(y_test, pred))

# 6. Save this experiment separately, preserving previous results
project = os.path.dirname(os.getcwd())
output = os.path.join(project, "ml_results")
os.makedirs(output, exist_ok=True)

joblib.dump(best_model, os.path.join(output, "banking_default_model_v2.joblib"))
comparison.to_csv(os.path.join(output, "model_comparison_v2.csv"), index=False)

pd.DataFrame({
    "actual_default": y_test.to_numpy(),
    "predicted_default": pred,
    "default_probability": prob
}).to_csv(os.path.join(output, "test_predictions_v2.csv"), index=False)

print("\nSaved new experiment to:", output)
print("Previous model files remain unchanged.")

CROSS-VALIDATED MODEL COMPARISON
              Model  CV_ROC_AUC_Mean  CV_ROC_AUC_Std
Logistic Regression         0.506414        0.023266
        Extra Trees         0.480965        0.035547
      Random Forest         0.480868        0.015089
  Gradient Boosting         0.476779        0.052494

SELECTED MODEL: Logistic Regression
Test accuracy: 0.5075
Balanced accuracy: 0.5277
Test ROC-AUC: 0.5225
Average precision: 0.1052
Default precision: 0.1045
Default recall: 0.5526
Default F1: 0.1757

CLASSIFICATION REPORT
              precision    recall  f1-score   support

 Non-default       0.91      0.50      0.65       362
     Default       0.10      0.55      0.18        38

    accuracy                           0.51       400
   macro avg       0.51      0.53      0.41       400
weighted avg       0.84      0.51      0.60       400

CONFUSION MATRIX
[[182 180]
 [ 17  21]]

Saved new experiment to: /Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/ml_results
Previous model files remain unchanged.

In [14]:
# ============================================================
# BANKING CUSTOMER RISK & LOAN INTELLIGENCE
# Improved Synthetic Default Prediction Experiment
# ============================================================

from pathlib import Path
import json
import warnings
import numpy as np
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

warnings.filterwarnings("ignore")

# ------------------------------------------------------------
# 1. FIND THE PROJECT AND LOAD THE ORIGINAL DATA
# ------------------------------------------------------------

possible_roots = [
    Path.cwd(),
    Path.cwd().parent,
    Path.home() / "Desktop" / "AI" / "Banking-Customer-Risk-Loan-Intelligence"
]

project_root = None

for root in possible_roots:
    if (
        (root / "data" / "customers.csv").exists()
        and (root / "data" / "Loans.csv").exists()
    ):
        project_root = root
        break

if project_root is None:
    raise FileNotFoundError(
        "Could not locate data/customers.csv and data/Loans.csv. "
        "Open this notebook from your Banking-Customer-Risk-Loan-Intelligence project."
    )

customers = pd.read_csv(project_root / "data" / "customers.csv")
loans = pd.read_csv(project_root / "data" / "Loans.csv")

print("Project folder:", project_root)
print("Customers:", customers.shape)
print("Loans:", loans.shape)

# ------------------------------------------------------------
# 2. JOIN CUSTOMER AND LOAN INFORMATION
# ------------------------------------------------------------

df = loans.merge(
    customers,
    on="customer_id",
    how="left",
    validate="many_to_one"
)

required_columns = [
    "loan_type", "loan_amount", "interest_rate",
    "age", "annual_income"
]

missing_columns = [c for c in required_columns if c not in df.columns]

if missing_columns:
    raise ValueError(f"Missing required columns: {missing_columns}")

# Convert numeric columns safely
for col in ["loan_amount", "interest_rate", "age", "annual_income"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Remove rows missing essential inputs
df = df.dropna(
    subset=["loan_type", "loan_amount", "interest_rate", "age", "annual_income"]
).copy()

# Avoid division by zero
df["annual_income"] = df["annual_income"].clip(lower=1)

# ------------------------------------------------------------
# 3. ENGINEER RISK FEATURES
# ------------------------------------------------------------

df["loan_to_income"] = (
    df["loan_amount"] / df["annual_income"]
)

df["income_per_month"] = (
    df["annual_income"] / 12
)

# A simple age-risk indicator; it is an assumption, not a fact
df["age_risk"] = (
    (df["age"] < 25) | (df["age"] > 60)
).astype(int)

# Loan-type risk weights are explicit synthetic assumptions
loan_type_risk = {
    "Personal": 0.45,
    "Business": 0.35,
    "Auto": 0.10,
    "Education": 0.00,
    "Home": -0.20
}

df["loan_type_risk"] = (
    df["loan_type"].astype(str).map(loan_type_risk).fillna(0)
)

# ------------------------------------------------------------
# 4. GENERATE A SEPARATE SYNTHETIC DEFAULT TARGET
# ------------------------------------------------------------
# IMPORTANT:
# These are simulated labels generated from explicit assumptions.
# They are NOT the original observed loan_status labels.

# Standardize features for stable risk-score construction
interest_z = (
    (df["interest_rate"] - df["interest_rate"].mean())
    / (df["interest_rate"].std() + 1e-9)
).clip(-3, 3)

loan_ratio_z = (
    (df["loan_to_income"] - df["loan_to_income"].mean())
    / (df["loan_to_income"].std() + 1e-9)
).clip(-3, 3)

income_z = (
    (df["annual_income"] - df["annual_income"].mean())
    / (df["annual_income"].std() + 1e-9)
).clip(-3, 3)

# Higher interest and higher loan-to-income increase simulated risk.
# Higher income slightly reduces risk. Age and loan type also contribute.
risk_score = (
    0.95 * interest_z
    + 1.05 * loan_ratio_z
    - 0.40 * income_z
    + 0.35 * df["age_risk"]
    + 0.75 * df["loan_type_risk"]
)

# Calibrate probabilities to an average default probability of 9.5%
target_default_rate = 0.095

def sigmoid(x):
    return 1 / (1 + np.exp(-np.clip(x, -30, 30)))

low, high = -20.0, 20.0

for _ in range(100):
    midpoint = (low + high) / 2
    mean_probability = sigmoid(risk_score + midpoint).mean()

    if mean_probability > target_default_rate:
        high = midpoint
    else:
        low = midpoint

intercept = (low + high) / 2
df["synthetic_default_probability"] = sigmoid(risk_score + intercept)

# Fixed seed makes the experiment reproducible
rng = np.random.default_rng(42)

df["synthetic_default_flag"] = rng.binomial(
    1, df["synthetic_default_probability"]
)

# Save a separate dataset; original files are untouched
output_dir = project_root / "ml_results"
output_dir.mkdir(parents=True, exist_ok=True)

dataset_path = output_dir / "synthetic_default_risk_dataset.csv"
df.to_csv(dataset_path, index=False)

print("\nSynthetic dataset created.")
print("Rows:", len(df))
print("Synthetic defaults:", int(df["synthetic_default_flag"].sum()))
print(
    "Synthetic default rate:",
    f"{df['synthetic_default_flag'].mean():.2%}"
)
print("Saved dataset:", dataset_path)

# ------------------------------------------------------------
# 5. SELECT MODEL INPUT FEATURES
# ------------------------------------------------------------

numeric_features = [
    "loan_amount",
    "interest_rate",
    "age",
    "annual_income",
    "loan_to_income",
    "age_risk"
]

categorical_features = ["loan_type"]

X = df[numeric_features + categorical_features].copy()
y = df["synthetic_default_flag"].copy()

# ------------------------------------------------------------
# 6. TRAIN / TEST SPLIT
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

# ------------------------------------------------------------
# 7. COMPARE THREE MODELS
# ------------------------------------------------------------

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=400,
        min_samples_leaf=5,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ),

    "Gradient Boosting": HistGradientBoostingClassifier(
        max_iter=150,
        learning_rate=0.06,
        max_leaf_nodes=15,
        l2_regularization=1.0,
        random_state=42
    )
}

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

results = []
trained_models = {}

for model_name, estimator in models.items():

    pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", estimator)
    ])

    cv_scores = cross_val_score(
        pipeline,
        X_train,
        y_train,
        cv=cv,
        scoring="roc_auc",
        n_jobs=-1
    )

    pipeline.fit(X_train, y_train)

    probabilities = pipeline.predict_proba(X_test)[:, 1]
    predictions = (probabilities >= 0.50).astype(int)

    results.append({
        "Model": model_name,
        "CV_ROC_AUC_Mean": cv_scores.mean(),
        "CV_ROC_AUC_Std": cv_scores.std(),
        "Test_Accuracy": accuracy_score(y_test, predictions),
        "Test_Balanced_Accuracy": balanced_accuracy_score(
            y_test, predictions
        ),
        "Test_ROC_AUC": roc_auc_score(y_test, probabilities),
        "Test_Average_Precision": average_precision_score(
            y_test, probabilities
        ),
        "Default_Precision": precision_score(
            y_test, predictions, zero_division=0
        ),
        "Default_Recall": recall_score(
            y_test, predictions, zero_division=0
        ),
        "Default_F1": f1_score(
            y_test, predictions, zero_division=0
        )
    })

    trained_models[model_name] = pipeline

results_df = pd.DataFrame(results).sort_values(
    "CV_ROC_AUC_Mean",
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 65)
print("MODEL COMPARISON")
print("=" * 65)
print(results_df.round(4).to_string(index=False))

results_df.to_csv(
    output_dir / "synthetic_model_comparison.csv",
    index=False
)

# ------------------------------------------------------------
# 8. SAVE AND EVALUATE THE MODEL SELECTED BY CROSS-VALIDATION
# ------------------------------------------------------------

best_name = results_df.iloc[0]["Model"]
best_model = trained_models[best_name]

best_probabilities = best_model.predict_proba(X_test)[:, 1]
best_predictions = (best_probabilities >= 0.50).astype(int)

joblib.dump(
    best_model,
    output_dir / "synthetic_default_risk_model.joblib"
)

evaluation = {
    "experiment": "Synthetic default-risk prediction",
    "target": "synthetic_default_flag",
    "best_model": best_name,
    "training_rows": int(len(X_train)),
    "test_rows": int(len(X_test)),
    "synthetic_default_rate": float(y.mean()),
    "test_accuracy": float(accuracy_score(y_test, best_predictions)),
    "test_balanced_accuracy": float(
        balanced_accuracy_score(y_test, best_predictions)
    ),
    "test_roc_auc": float(
        roc_auc_score(y_test, best_probabilities)
    ),
    "test_average_precision": float(
        average_precision_score(y_test, best_probabilities)
    ),
    "default_precision": float(
        precision_score(y_test, best_predictions, zero_division=0)
    ),
    "default_recall": float(
        recall_score(y_test, best_predictions, zero_division=0)
    ),
    "default_f1": float(
        f1_score(y_test, best_predictions, zero_division=0)
    ),
    "confusion_matrix": confusion_matrix(
        y_test, best_predictions
    ).tolist(),
    "note": (
        "Target labels were simulated from assumed risk relationships. "
        "Results demonstrate a synthetic ML workflow and do not establish "
        "real-world default prediction performance."
    )
}

with open(output_dir / "synthetic_model_evaluation.json", "w") as f:
    json.dump(evaluation, f, indent=4)

predictions_df = X_test.copy()
predictions_df["actual_synthetic_default"] = y_test.values
predictions_df["predicted_default_probability"] = best_probabilities
predictions_df["predicted_synthetic_default"] = best_predictions

predictions_df.to_csv(
    output_dir / "synthetic_test_predictions.csv",
    index=False
)

print("\n" + "=" * 65)
print("BEST MODEL EVALUATION")
print("=" * 65)
print("Selected model:", best_name)
print(f"Accuracy: {evaluation['test_accuracy']:.4f}")
print(f"Balanced accuracy: {evaluation['test_balanced_accuracy']:.4f}")
print(f"ROC-AUC: {evaluation['test_roc_auc']:.4f}")
print(f"Average precision: {evaluation['test_average_precision']:.4f}")
print(f"Default precision: {evaluation['default_precision']:.4f}")
print(f"Default recall: {evaluation['default_recall']:.4f}")
print(f"Default F1-score: {evaluation['default_f1']:.4f}")

print("\nConfusion matrix:")
print(np.array(evaluation["confusion_matrix"]))

print("\nClassification report:")
print(classification_report(
    y_test,
    best_predictions,
    target_names=["Non-default", "Synthetic default"],
    zero_division=0
))

print("\nSaved all experiment files in:")
print(output_dir)
print("\nOriginal customer and loan CSV files were not modified.")

Project folder: /Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence
Customers: (10000, 7)
Loans: (2000, 8)

Synthetic dataset created.
Rows: 2000
Synthetic defaults: 176
Synthetic default rate: 8.80%
Saved dataset: /Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/ml_results/synthetic_default_risk_dataset.csv

=================================================================
MODEL COMPARISON
=================================================================
              Model  CV_ROC_AUC_Mean  CV_ROC_AUC_Std  Test_Accuracy  Test_Balanced_Accuracy  Test_ROC_AUC  Test_Average_Precision  Default_Precision  Default_Recall  Default_F1
Logistic Regression           0.8285          0.0446          0.762                  0.7155        0.8172                  0.4145             0.2180          0.6591      0.3277
      Random Forest           0.8199          0.0507          0.850                  0.7124        0.7669                  0.3899             0.3038          0.5455      0.3902
  Gradient Boosting           0.7926          0.0540          0.920                  0.6687        0.7673                  0.3726             0.5714          0.3636      0.4444

=================================================================
BEST MODEL EVALUATION
=================================================================
Selected model: Logistic Regression
Accuracy: 0.7620
Balanced accuracy: 0.7155
ROC-AUC: 0.8172
Average precision: 0.4145
Default precision: 0.2180
Default recall: 0.6591
Default F1-score: 0.3277

Confusion matrix:
[[352 104]
 [ 15  29]]

Classification report:
                   precision    recall  f1-score   support

      Non-default       0.96      0.77      0.86       456
Synthetic default       0.22      0.66      0.33        44

         accuracy                           0.76       500
        macro avg       0.59      0.72      0.59       500
     weighted avg       0.89      0.76      0.81       500


Saved all experiment files in:
/Users/bensonmartin/Desktop/AI/Banking-Customer-Risk-Loan-Intelligence/ml_results

Original customer and loan CSV files were not modified.

In [15]:
# Check whether the trained model and preprocessing objects exist

print("Available model-related variables:")

for name in [
    "best_model",
    "best_pipeline",
    "best_lr",
    "logistic_model",
    "X_train",
    "X_test",
    "y_train",
    "y_test"
]:
    if name in globals():
        print(f"{name}: Available")

Available model-related variables:
best_model: Available
X_train: Available
X_test: Available
y_train: Available
y_test: Available